import { systemClock, type Clock } from './clock.js';
import { matchesController } from './matcher.js';
import {
  REJECT_REASONS, decodeDeviceReport, encodeReport, isRgb, ledFrameReports, LED_COUNT,
  type HeartbeatMessage, type HelloMessage, type InputKind, type InputMessage, type RejectReason, type Rgb,
} from './protocol.js';
import { Subscription } from './subscription.js';
import type { HidDeviceInfo, Transport, TransportConnection } from './transport.js';

/** Version of the event/feedback interface below. A breaking change to any exported type increments it. */
export const BRIDGE_INTERFACE_VERSION = 1;

export interface BridgeTiming {
  /** Host heartbeat period; the protocol fixes it at 500 ms. */
  hostHeartbeatMs: number;
  /** Without a device heartbeat for this long, the link is stale and held controls are released. */
  staleAfterMs: number;
  /** Without a device heartbeat for this long, the handle is closed and the device is searched for again. */
  disconnectAfterMs: number;
  /** After opening, the bridge stays silent this long so the firmware sees the host as absent (its timeout is 2 s). */
  helloQuietMs: number;
  /** After the quiet period, heartbeats solicit a hello for this long before the open is retried. */
  helloTimeoutMs: number;
  /** Delay before enumerating again after a failed search, open or disconnect. */
  reconnectMs: number;
  /** An LED frame the device has not reported as applied is resent after this long. */
  ledResendMs: number;
  /** Minimum time between LED frames; newer frames replace a waiting one. */
  ledMinIntervalMs: number;
}

export const DEFAULT_TIMING: Readonly<BridgeTiming> = Object.freeze({
  hostHeartbeatMs: 500,
  staleAfterMs: 1500,
  disconnectAfterMs: 5000,
  helloQuietMs: 2500,
  helloTimeoutMs: 3000,
  reconnectMs: 1000,
  ledResendMs: 1000,
  ledMinIntervalMs: 40,
});

export type DisconnectReason = 'device-closed' | 'transport-error' | 'heartbeat-timeout' | 'epoch-change' | 'stopped';
export type ReleaseReason = DisconnectReason | 'stale';

/** A compatible hello started a connection epoch. Input is accepted only within it. */
export interface ConnectedEvent { type: 'connected'; at: number; epoch: number; firmware: [number, number, number] }
/**
 * One physical event. `synthetic` releases are generated by the bridge when it can no longer see a held control
 * (disconnect, stale link, epoch change or stop); they have no sequence and carry the reason.
 */
export type InputEvent =
  | { type: 'input'; at: number; epoch: number; sequence: number; control: number; kind: InputKind; delta: number; synthetic: false }
  | { type: 'input'; at: number; epoch: number; sequence: null; control: number; kind: 'release'; delta: 0; synthetic: true; reason: ReleaseReason };
/** No device heartbeat for `staleAfterMs`. A link state only; it says nothing about any task. */
export interface StaleEvent { type: 'stale'; at: number; epoch: number }
/** Heartbeats resumed in the same epoch. Controls released at `stale` need a fresh press. */
export interface RecoveredEvent { type: 'recovered'; at: number; epoch: number }
/** The connection epoch ended. Every held control was released before this event. */
export interface DisconnectedEvent { type: 'disconnected'; at: number; epoch: number; reason: DisconnectReason }
export type BridgeEvent = ConnectedEvent | InputEvent | StaleEvent | RecoveredEvent | DisconnectedEvent;

export type BridgeState = 'idle' | 'searching' | 'awaiting-hello' | 'connected' | 'stale' | 'stopped';

export interface BridgeCounters {
  malformed: Record<RejectReason, number>;
  beforeHello: number;
  otherEpoch: number;
  duplicateSequence: number;
  olderSequence: number;
  whileStale: number;
  repeatedPress: number;
  orphanRelease: number;
  duplicateHello: number;
  helloTimeouts: number;
  ambiguousDevices: number;
  enumerationErrors: number;
  openErrors: number;
  transportErrors: number;
  ledResends: number;
  subscriberOverflows: number;
}

export interface BridgeStatus {
  state: BridgeState;
  epoch: number | null;
  firmware: [number, number, number] | null;
  /** The device's own view of host heartbeats, from its last heartbeat. */
  deviceHostAlive: boolean | null;
  appliedLedFrame: number | null;
  pendingLedFrame: number | null;
  brightnessPercent: number;
  held: number[];
  counters: BridgeCounters;
}

export type BridgeSubscription = Subscription<BridgeEvent>;

export interface ChompiBridge {
  readonly interfaceVersion: typeof BRIDGE_INTERFACE_VERSION;
  /** Starts searching for the controller. The caller must already hold the single-instance lock. */
  start(): void;
  /** Releases held controls, closes the device and ends every subscription. */
  stop(): Promise<void>;
  /** A bounded event queue (default 256). A subscriber that falls behind is closed with reason `overflow`. */
  events(options?: { limit?: number }): BridgeSubscription;
  /** Sets all 35 LED colors (RGB 0-255, in LED index order). Resent after reconnect until replaced. */
  setLeds(colors: readonly Rgb[]): void;
  /** Host brightness percent (0-100) sent in every host heartbeat; the firmware applies its own caps after it. */
  setBrightness(percent: number): void;
  status(): BridgeStatus;
}

export interface ChompiBridgeOptions {
  transport: Transport;
  clock?: Clock;
  /** Open only the controller with this serial. Without it, two matching controllers are refused. */
  serialNumber?: string;
  /** Profile version reported to the firmware in host heartbeats (u32). */
  profileVersion?: number;
  brightnessPercent?: number;
  timing?: Partial<BridgeTiming>;
}

interface Session {
  epoch: number;
  firmware: [number, number, number];
  lastSequence: number | undefined;
  held: Set<number>;
  heardHeartbeat: boolean;
  deviceHostAlive: boolean | null;
  nextFrame: number;
  appliedFrame: number | null;
  sentFrame: number | undefined;
  sentColors: Rgb[] | undefined;
  sentAt: number;
  lastLedSendAt: number | undefined;
}

type TimerName = 'reconnect' | 'quiet' | 'hello' | 'beat' | 'stale' | 'silent' | 'led';

interface Link { token: object; connection: TransportConnection | undefined; writes: Promise<void>; pending: number }

/** Writes queued on one handle beyond this mean the device stopped accepting reports. */
const MAX_PENDING_WRITES = 32;

const zeroCounters = (): BridgeCounters => ({
  malformed: Object.fromEntries(REJECT_REASONS.map(reason => [reason, 0])) as Record<RejectReason, number>,
  beforeHello: 0, otherEpoch: 0, duplicateSequence: 0, olderSequence: 0, whileStale: 0, repeatedPress: 0, orphanRelease: 0,
  duplicateHello: 0, helloTimeouts: 0, ambiguousDevices: 0, enumerationErrors: 0, openErrors: 0, transportErrors: 0,
  ledResends: 0, subscriberOverflows: 0,
});

function checkBrightness(percent: number): number {
  if (!Number.isInteger(percent) || percent < 0 || percent > 100) throw new RangeError('brightness must be an integer percent 0-100');
  return percent;
}

/** Creates the connection manager. It touches no device until `start`. */
export function createChompiBridge(options: ChompiBridgeOptions): ChompiBridge {
  return new Bridge(options);
}

class Bridge implements ChompiBridge {
  readonly interfaceVersion = BRIDGE_INTERFACE_VERSION;
  readonly #transport: Transport;
  readonly #clock: Clock;
  readonly #timing: BridgeTiming;
  readonly #serial: string | undefined;
  readonly #profileVersion: number;
  readonly #subscriptions = new Set<BridgeSubscription>();
  readonly #counters = zeroCounters();
  #brightness: number;
  #state: BridgeState = 'idle';
  #link: Link | undefined;
  #session: Session | undefined;
  #desired: Rgb[] | undefined;
  #ledDirty = false;
  #heartbeating = false;
  #timers: Partial<Record<TimerName, unknown>> = {};
  #stopping: Promise<void> | undefined;

  constructor(options: ChompiBridgeOptions) {
    this.#transport = options.transport;
    this.#clock = options.clock ?? systemClock;
    this.#timing = { ...DEFAULT_TIMING, ...options.timing };
    this.#serial = options.serialNumber;
    const profile = options.profileVersion ?? 0;
    if (!Number.isInteger(profile) || profile < 0 || profile > 0xffffffff) throw new RangeError('profileVersion must be a u32');
    this.#profileVersion = profile;
    this.#brightness = checkBrightness(options.brightnessPercent ?? 100);
  }

  start(): void {
    if (this.#state !== 'idle') return;
    this.#state = 'searching';
    void this.#search();
  }

  stop(): Promise<void> {
    this.#stopping ??= this.#stop();
    return this.#stopping;
  }

  events(options: { limit?: number } = {}): BridgeSubscription {
    const subscription = new Subscription<BridgeEvent>(options.limit ?? 256, s => this.#subscriptions.delete(s));
    if (this.#state === 'stopped') subscription.stop();
    else this.#subscriptions.add(subscription);
    return subscription;
  }

  setLeds(colors: readonly Rgb[]): void {
    if (colors.length !== LED_COUNT || !colors.every(isRgb)) throw new RangeError(`setLeds needs ${LED_COUNT} RGB triples of integers 0-255`);
    this.#desired = colors.map(([r, g, b]) => [r, g, b] as const);
    this.#ledDirty = true;
    this.#flushLeds();
  }

  setBrightness(percent: number): void {
    this.#brightness = checkBrightness(percent);
    if (this.#heartbeating) this.#sendHostHeartbeat();
  }

  status(): BridgeStatus {
    const s = this.#session;
    return {
      state: this.#state,
      epoch: s?.epoch ?? null,
      firmware: s ? [...s.firmware] : null,
      deviceHostAlive: s?.deviceHostAlive ?? null,
      appliedLedFrame: s?.appliedFrame ?? null,
      pendingLedFrame: s?.sentFrame ?? null,
      brightnessPercent: this.#brightness,
      held: s ? [...s.held].sort((a, b) => a - b) : [],
      counters: { ...this.#counters, malformed: { ...this.#counters.malformed } },
    };
  }

  // Search and open

  async #search(): Promise<void> {
    if (this.#state !== 'searching') return;
    let devices: HidDeviceInfo[];
    try {
      devices = await this.#transport.list();
    } catch {
      this.#counters.enumerationErrors++;
      return this.#scheduleSearch();
    }
    if (this.#state !== 'searching') return;
    const matches = devices.filter(device => matchesController(device, this.#serial));
    if (matches.length !== 1) {
      if (matches.length > 1) this.#counters.ambiguousDevices++;
      return this.#scheduleSearch();
    }
    const link: Link = { token: {}, connection: undefined, writes: Promise.resolve(), pending: 0 };
    this.#link = link;
    this.#state = 'awaiting-hello';
    let connection: TransportConnection;
    try {
      connection = await this.#transport.open(matches[0]!, {
        report: report => this.#onReport(link, report),
        closed: error => this.#onClosed(link, error),
      });
    } catch {
      this.#counters.openErrors++;
      if (this.#link === link) this.#drop('transport-error');
      return;
    }
    if (this.#link !== link) {
      void connection.close().catch(() => undefined);
      return;
    }
    link.connection = connection;
    if (this.#state === 'awaiting-hello') this.#timers.quiet = this.#clock.setTimeout(() => this.#solicitHello(link), this.#timing.helloQuietMs);
  }

  #scheduleSearch(): void {
    if (this.#state === 'stopped' || this.#timers.reconnect !== undefined) return;
    this.#state = 'searching';
    this.#timers.reconnect = this.#clock.setTimeout(() => {
      delete this.#timers.reconnect;
      void this.#search();
    }, this.#timing.reconnectMs);
  }

  /** The firmware sends `hello` at enumeration, which an already-running device sent before this handle existed. */
  #solicitHello(link: Link): void {
    delete this.#timers.quiet;
    if (this.#link !== link || this.#state !== 'awaiting-hello') return;
    this.#startHeartbeats();
    this.#timers.hello = this.#clock.setTimeout(() => {
      delete this.#timers.hello;
      if (this.#link !== link || this.#state !== 'awaiting-hello') return;
      this.#counters.helloTimeouts++;
      this.#drop('device-closed');
    }, this.#timing.helloTimeoutMs);
  }

  // Device reports

  #onReport(link: Link, report: Uint8Array): void {
    if (this.#link !== link) return;
    const decoded = decodeDeviceReport(report);
    if (!decoded.ok) {
      this.#counters.malformed[decoded.reason]++;
      return;
    }
    const message = decoded.message;
    if (message.type === 'hello') this.#onHello(message);
    else if (message.type === 'heartbeat') this.#onHeartbeat(message);
    else this.#onInput(message);
  }

  #onHello(message: HelloMessage): void {
    if (message.epoch === 0) {
      this.#counters.malformed['incompatible-device']++;
      return;
    }
    if (this.#session?.epoch === message.epoch) {
      this.#counters.duplicateHello++;
      return;
    }
    if (this.#session) this.#endSession('epoch-change');
    this.#clearTimers('quiet', 'hello');
    this.#session = {
      epoch: message.epoch, firmware: [...message.firmware], lastSequence: undefined, held: new Set(), heardHeartbeat: false,
      deviceHostAlive: null, nextFrame: 0, appliedFrame: null, sentFrame: undefined, sentColors: undefined, sentAt: 0, lastLedSendAt: undefined,
    };
    this.#state = 'connected';
    this.#ledDirty = this.#desired !== undefined;
    this.#emit({ type: 'connected', at: this.#clock.now(), epoch: message.epoch, firmware: [...message.firmware] });
    this.#startHeartbeats();
    this.#armSilenceTimers();
  }

  #onHeartbeat(message: HeartbeatMessage): void {
    const session = this.#session;
    if (!session) return void this.#counters.beforeHello++;
    if (message.epoch !== session.epoch) return void this.#counters.otherEpoch++;
    session.deviceHostAlive = message.hostAlive;
    this.#armSilenceTimers();
    if (this.#state === 'stale') {
      this.#state = 'connected';
      this.#emit({ type: 'recovered', at: this.#clock.now(), epoch: session.epoch });
    }
    if (!session.heardHeartbeat) {
      session.heardHeartbeat = true;
      session.nextFrame = (message.ledFrame + 1) & 0xffff;
    }
    session.appliedFrame = message.ledFrame;
    if (session.sentFrame === message.ledFrame) {
      session.sentFrame = undefined;
      session.sentColors = undefined;
    }
    this.#flushLeds();
  }

  #onInput(message: InputMessage): void {
    const session = this.#session;
    if (!session) return void this.#counters.beforeHello++;
    if (message.epoch !== session.epoch) return void this.#counters.otherEpoch++;
    if (this.#state === 'stale') return void this.#counters.whileStale++;
    if (session.lastSequence !== undefined) {
      const ahead = (message.sequence - session.lastSequence) & 0xffff;
      if (ahead === 0) return void this.#counters.duplicateSequence++;
      if (ahead >= 0x8000) return void this.#counters.olderSequence++;
    }
    session.lastSequence = message.sequence;
    if (message.kind === 'press') {
      if (session.held.has(message.control)) return void this.#counters.repeatedPress++;
      session.held.add(message.control);
    } else if (message.kind === 'release') {
      if (!session.held.delete(message.control)) return void this.#counters.orphanRelease++;
    }
    this.#emit({
      type: 'input', at: this.#clock.now(), epoch: session.epoch, sequence: message.sequence, control: message.control,
      kind: message.kind, delta: message.delta, synthetic: false,
    });
  }

  #onClosed(link: Link, error?: Error): void {
    if (this.#link !== link) return;
    if (error) this.#counters.transportErrors++;
    this.#drop('device-closed');
  }

  // Liveness

  #armSilenceTimers(): void {
    this.#clearTimers('stale', 'silent');
    this.#timers.stale = this.#clock.setTimeout(() => {
      delete this.#timers.stale;
      const session = this.#session;
      if (!session || this.#state !== 'connected') return;
      this.#state = 'stale';
      this.#releaseHeld(session, 'stale');
      this.#emit({ type: 'stale', at: this.#clock.now(), epoch: session.epoch });
    }, this.#timing.staleAfterMs);
    this.#timers.silent = this.#clock.setTimeout(() => {
      delete this.#timers.silent;
      this.#drop('heartbeat-timeout');
    }, this.#timing.disconnectAfterMs);
  }

  #startHeartbeats(): void {
    this.#clearTimers('beat');
    this.#heartbeating = true;
    this.#sendHostHeartbeat();
    this.#timers.beat = this.#clock.setInterval(() => this.#beat(), this.#timing.hostHeartbeatMs);
  }

  #beat(): void {
    this.#sendHostHeartbeat();
    const session = this.#session;
    if (this.#state === 'connected' && session?.sentFrame !== undefined && session.sentColors
      && this.#clock.now() - session.sentAt >= this.#timing.ledResendMs) {
      this.#counters.ledResends++;
      this.#sendFrame(session, session.sentFrame, session.sentColors);
    }
  }

  #sendHostHeartbeat(): void {
    this.#write(encodeReport({ type: 'host-heartbeat', version: 1, profileVersion: this.#profileVersion, brightnessPercent: this.#brightness }));
  }

  // LEDs

  #flushLeds(): void {
    const session = this.#session;
    if (!session?.heardHeartbeat || this.#state !== 'connected' || !this.#ledDirty || !this.#desired) return;
    if (this.#timers.led !== undefined) return;
    const wait = session.lastLedSendAt === undefined ? 0 : session.lastLedSendAt + this.#timing.ledMinIntervalMs - this.#clock.now();
    if (wait > 0) {
      this.#timers.led = this.#clock.setTimeout(() => {
        delete this.#timers.led;
        this.#flushLeds();
      }, wait);
      return;
    }
    const frame = session.nextFrame;
    session.nextFrame = (frame + 1) & 0xffff;
    this.#ledDirty = false;
    this.#sendFrame(session, frame, this.#desired);
  }

  #sendFrame(session: Session, frame: number, colors: Rgb[]): void {
    session.sentFrame = frame;
    session.sentColors = colors;
    session.sentAt = this.#clock.now();
    session.lastLedSendAt = session.sentAt;
    for (const report of ledFrameReports(frame, colors)) this.#write(report);
  }

  // Connection teardown

  #write(report: Uint8Array): void {
    const link = this.#link;
    const connection = link?.connection;
    if (!link || !connection) return;
    if (link.pending >= MAX_PENDING_WRITES) {
      this.#counters.transportErrors++;
      this.#drop('transport-error');
      return;
    }
    link.pending++;
    link.writes = link.writes.then(() => connection.write(report)).then(() => { link.pending--; }, () => {
      if (this.#link !== link) return;
      this.#counters.transportErrors++;
      this.#drop('transport-error');
    });
  }

  #releaseHeld(session: Session, reason: ReleaseReason): void {
    for (const control of [...session.held].sort((a, b) => a - b)) {
      this.#emit({ type: 'input', at: this.#clock.now(), epoch: session.epoch, sequence: null, control, kind: 'release', delta: 0, synthetic: true, reason });
    }
    session.held.clear();
  }

  #endSession(reason: DisconnectReason): void {
    const session = this.#session;
    if (!session) return;
    this.#clearTimers('stale', 'silent', 'led');
    this.#releaseHeld(session, reason);
    this.#session = undefined;
    this.#emit({ type: 'disconnected', at: this.#clock.now(), epoch: session.epoch, reason });
  }

  /** Ends the session and handle, then searches again unless stopping. */
  #drop(reason: DisconnectReason): void {
    const link = this.#link;
    this.#link = undefined;
    this.#heartbeating = false;
    this.#clearTimers('quiet', 'hello', 'beat');
    this.#endSession(reason);
    if (link?.connection) void link.connection.close().catch(() => undefined);
    if (this.#state !== 'stopped') {
      this.#state = 'searching';
      this.#scheduleSearch();
    }
  }

  async #stop(): Promise<void> {
    const link = this.#link;
    this.#state = 'stopped';
    this.#link = undefined;
    this.#heartbeating = false;
    this.#clearTimers('reconnect', 'quiet', 'hello', 'beat', 'stale', 'silent', 'led');
    this.#endSession('stopped');
    for (const subscription of [...this.#subscriptions]) subscription.stop();
    // Pending writes are not awaited: a stalled device must not block shutdown. Closing rejects them.
    if (link?.connection) await link.connection.close().catch(() => undefined);
  }

  #clearTimers(...names: TimerName[]): void {
    for (const name of names) {
      const handle = this.#timers[name];
      if (handle === undefined) continue;
      this.#clock.clearTimeout(handle);
      this.#clock.clearInterval(handle);
      delete this.#timers[name];
    }
  }

  #emit(event: BridgeEvent): void {
    for (const subscription of [...this.#subscriptions]) if (!subscription.push(event)) this.#counters.subscriberOverflows++;
  }
}
