// Existing playlist editing through the shared tracked command UI, using fresh synthetic state (Hub #932).
import assert from 'node:assert/strict';
import {setTimeout as delay} from 'node:timers/promises';
import {AxeBuilder} from '@axe-core/playwright';
import {chromium, type Browser} from 'playwright';
import sharp from 'sharp';
import {changes, feed, startWorld} from './harness.ts';

const world = await startWorld({pixooPages: true});
let browser: Browser | undefined;
try {
  browser = await chromium.launch({headless: true});
  const context = await browser.newContext({viewport: {width: 1440, height: 900}, reducedMotion: 'reduce'});
  try {
    const errors: string[] = []; context.on('weberror', error => {errors.push(error.error().name);});
    const page = await context.newPage(); page.setDefaultTimeout(8000);
    page.on('dialog', dialog => {void dialog.accept();});
    const sent = changes(page);
    let refusedSyncs = 0;
    await page.route('**/api/sdk/v1/sync', async route => {
      const body = route.request().postDataJSON() as {request?: {data?: {families?: string[]}}};
      if (refusedSyncs === 0 && body.request?.data?.families?.includes('pixoo-playlist') === true) {
        refusedSyncs++;
        await route.fulfill({status: 503, contentType: 'application/json', body: '{"error":{"code":"unavailable","retryable":true}}'});
      } else await route.continue();
    });
    await page.goto(`${world.url}/#/module/pixoo/playlists`); await feed(page, 'connected');
    await page.getByRole('alert').filter({hasText: 'Pixoo records unavailable (unavailable).'}).waitFor();
    assert.equal(refusedSyncs, 1); assert.equal(sent.length, 0, 'a failed catalog observation sends no mutation');
    await page.getByRole('button', {name: 'Retry Pixoo records', exact: true}).click();
    await page.getByRole('textbox', {name: 'New playlist name', exact: true}).waitFor();
    await page.waitForFunction(() => document.querySelector('input[autocomplete="off"]')?.hasAttribute('disabled') === false);
    assert.equal(await page.getByRole('alert').filter({hasText: 'Pixoo records unavailable'}).count(), 0);
    assert.equal(sent.length, 0, 'explicit sync recovery never retries a command');
    await page.getByRole('textbox', {name: 'New playlist name', exact: true}).fill('Synthetic sequence');
    assert.equal(sent.length, 0, 'opening and drafting sends no command');
    assert.deepEqual(await world.pixooPlaylists(), []);
    const create = page.getByRole('button', {name: 'Create playlist', exact: true});
    await create.focus(); await create.press('Enter');
    for (let attempt = 0; (await world.pixooPlaylists()).length === 0 && attempt < 100; attempt++) await delay(20);
    const created = (await world.pixooPlaylists())[0]; assert.ok(created);
    assert.equal(created.name, 'Synthetic sequence'); assert.equal(sent.length, 1);
    await page.getByRole('combobox', {name: 'Playlist', exact: true}).selectOption(created.id);
    await page.getByRole('textbox', {name: 'Playlist name', exact: true}).fill('Renamed sequence');
    await page.getByRole('button', {name: 'Save name', exact: true}).click();
    for (let attempt = 0; (await world.pixooPlaylists())[0]?.name !== 'Renamed sequence' && attempt < 100; attempt++) await delay(20);
    assert.equal((await world.pixooPlaylists())[0]?.name, 'Renamed sequence'); assert.equal(sent.length, 2);
    await page.getByText('The saved playlist changed. Load its saved name before editing again.', {exact: true}).waitFor();
    assert.equal(await page.getByRole('button', {name: 'Save name', exact: true}).isDisabled(), true, 'a changed saved revision refuses the old draft');
    await page.getByRole('button', {name: 'Load saved name', exact: true}).click();
    await page.getByRole('checkbox', {name: 'Repeat playlist', exact: true}).check();
    await page.getByRole('checkbox', {name: 'Shuffle', exact: true}).check();
    assert.equal((await world.pixooPlaylists())[0]?.shuffle, false); assert.equal(sent.length, 2, 'option drafts send nothing');
    await page.getByRole('button', {name: 'Save options', exact: true}).click();
    for (let attempt = 0; (await world.pixooPlaylists())[0]?.shuffle !== true && attempt < 100; attempt++) await delay(20);
    const options = (await world.pixooPlaylists())[0]; assert.ok(options);
    assert.equal(options.repeat, true); assert.equal(options.shuffle, true); assert.equal(sent.length, 3);
    await page.getByRole('link', {name: 'Library', exact: true}).click();
    const png = await sharp({create: {width: 64, height: 64, channels: 3, background: {r: 20, g: 90, b: 150}}}).png().toBuffer();
    await page.getByLabel('Media file', {exact: true}).setInputFiles({name: 'Sequence still.png', mimeType: 'image/png', buffer: png});
    await page.getByRole('button', {name: 'Add media', exact: true}).click();
    for (let attempt = 0; (await world.pixooMedia()).items.length === 0 && attempt < 100; attempt++) await delay(20);
    assert.equal((await world.pixooMedia()).items.length, 1); assert.equal(sent.length, 4);
    await page.getByRole('link', {name: 'Playlists', exact: true}).click();
    await page.getByRole('combobox', {name: 'Playlist', exact: true}).selectOption(created.id);
    const media = page.getByRole('combobox', {name: 'Media to add', exact: true});
    const addedMedia = (await world.pixooMedia()).items[0]; assert.ok(addedMedia);
    await media.locator('option').filter({hasText: `Sequence still.png · rendition ${addedMedia.renditionId.slice(0, 10)}`}).waitFor({state: 'attached'});
    await media.selectOption(addedMedia.renditionId);
    await page.getByRole('group', {name: 'Selected rendition to add', exact: true}).getByRole('img', {name: 'Effective preview', exact: true}).waitFor();
    await page.getByRole('button', {name: 'Add selected media', exact: true}).click();
    await page.getByRole('button', {name: 'Add selected media', exact: true}).click();
    const thumbnail = page.getByRole('img', {name: 'Item 1 preview', exact: true});
    const pixel = (): Promise<number[]> => thumbnail.evaluate(node => {
      const canvas = node as HTMLCanvasElement;
      const context = canvas.getContext('2d');
      return context === null ? [] : Array.from(context.getImageData(0, 0, 1, 1).data).slice(0, 3);
    });
    for (let attempt = 0; JSON.stringify(await pixel()) !== '[20,90,150]' && attempt < 100; attempt++) await delay(20);
    assert.deepEqual(await pixel(), [20, 90, 150], 'the referenced synthetic thumbnail is decoded into the canvas');
    await page.getByRole('spinbutton', {name: 'Item 1 seconds', exact: true}).fill('0');
    assert.equal(await page.getByRole('button', {name: 'Save items', exact: true}).isDisabled(), true, 'invalid timing refuses save');
    await page.getByRole('spinbutton', {name: 'Item 1 seconds', exact: true}).fill('5');
    await page.getByRole('spinbutton', {name: 'Item 2 seconds', exact: true}).fill('9');
    assert.equal(sent.length, 4, 'adding and timing drafts sends nothing');
    assert.deepEqual((await world.pixooPlaylists())[0]?.items, []);
    await page.getByRole('button', {name: 'Save items', exact: true}).click();
    for (let attempt = 0; (await world.pixooPlaylists())[0]?.items.length !== 2 && attempt < 100; attempt++) await delay(20);
    const savedItems = (await world.pixooPlaylists())[0]; assert.ok(savedItems);
    assert.equal(savedItems.items.length, 2); assert.notEqual(savedItems.items[0]?.id, savedItems.items[1]?.id);
    assert.deepEqual(savedItems.items.map(item => item.playback), [{mode: 'duration', durationMs: 5000}, {mode: 'duration', durationMs: 9000}]);
    assert.equal(sent.length, 5);
    await page.getByRole('button', {name: 'Reload saved playlist', exact: true}).click();
    await page.getByRole('button', {name: 'Move item 1 down', exact: true}).click();
    assert.deepEqual((await world.pixooPlaylists())[0], savedItems); assert.equal(sent.length, 5);
    await page.getByRole('button', {name: 'Save items', exact: true}).click();
    for (let attempt = 0; (await world.pixooPlaylists())[0]?.playlistRevision === savedItems.playlistRevision && attempt < 100; attempt++) await delay(20);
    const reordered = (await world.pixooPlaylists())[0]; assert.ok(reordered);
    assert.deepEqual(reordered.items.map(item => item.id), [...savedItems.items].reverse().map(item => item.id)); assert.equal(sent.length, 6);
    await page.getByRole('button', {name: 'Reload saved playlist', exact: true}).click();
    await page.getByRole('button', {name: 'Remove item 2', exact: true}).click();
    assert.deepEqual((await world.pixooPlaylists())[0], reordered); assert.equal(sent.length, 6);
    await page.getByRole('button', {name: 'Save items', exact: true}).click();
    for (let attempt = 0; (await world.pixooPlaylists())[0]?.items.length !== 1 && attempt < 100; attempt++) await delay(20);
    assert.equal((await world.pixooPlaylists())[0]?.items.length, 1); assert.equal(sent.length, 7);
    await page.reload(); await feed(page, 'connected');
    await page.getByRole('combobox', {name: 'Playlist', exact: true}).selectOption(created.id);
    assert.equal(await page.getByRole('textbox', {name: 'Playlist name', exact: true}).inputValue(), 'Renamed sequence');
    assert.equal(sent.length, 7, 'reload never resends');
    assert.deepEqual((await new AxeBuilder({page}).withTags(['wcag2a', 'wcag2aa', 'wcag21aa']).analyze()).violations.map(item => item.id), []);
    const finalSaved = (await world.pixooPlaylists())[0]; assert.ok(finalSaved);
    await page.route('**/api/v2/authority?scope=control', route => route.fulfill({status: 403, contentType: 'application/json', body: '{"error":{"code":"forbidden","retryable":false}}'}));
    await page.reload(); await feed(page, 'connected');
    await page.getByRole('combobox', {name: 'Playlist', exact: true}).selectOption(created.id);
    await page.getByText('Read-only access.', {exact: true}).waitFor();
    assert.equal(await page.getByRole('button', {name: 'Create playlist', exact: true}).count(), 0);
    assert.equal(await page.getByRole('button', {name: 'Save items', exact: true}).count(), 0);
    assert.equal(await page.getByRole('button', {name: 'Save options', exact: true}).count(), 0);
    assert.equal(await world.readonlyPlaylistCommand({change: {operation: 'create', name: 'Denied'}}), 403);
    assert.deepEqual(await world.pixooPlaylists(), [finalSaved]); assert.equal(sent.length, 7);
    await page.unroute('**/api/v2/authority?scope=control');
    await page.reload(); await feed(page, 'connected');
    await page.getByRole('combobox', {name: 'Playlist', exact: true}).selectOption(created.id);
    await page.getByRole('button', {name: 'Delete playlist', exact: true}).click();
    for (let attempt = 0; (await world.pixooPlaylists()).length !== 0 && attempt < 100; attempt++) await delay(20);
    assert.deepEqual(await world.pixooPlaylists(), []); assert.equal(sent.length, 8);
    assert.equal(world.pixooState().sent, 0); assert.deepEqual(errors, []);
    process.stdout.write(`${JSON.stringify({passed: true, journey: 'pixoo-playlist-create-rename-options-items-order-remove-delete', requests: sent.length, referencedThumbnail: true, displayWrites: 0, readOnlyRefused: true, axe: 'passed'})}\n`);
  } finally {await context.close();}
} finally {try {await browser?.close();} finally {await world.close();}}
