import React, {useEffect,useRef,useState} from 'react';
import {createRoot} from 'react-dom/client';
import type {Snapshot as StateSnapshot,SessionSnapshot} from '../../../packages/agent-state/src/types';
import type {Snapshot,Mode} from '../../../packages/contracts/src/types';
import {Api,ApiError,makeCommand,safeEditorUrl,type Context,type Component} from './client';
import './style.css';

type Monitor={snapshot:StateSnapshot;nextRequestId:string;ownerId:string};
type Nano={apiVersion:string;identity:Snapshot['identity'];revision:string;configurationRevision:number;mode:string;settings:{style?:string;coverage?:string};source:string;projects:{id:string;color:string}[];tasks:{id:string;projectId:string|null;overrideProjectId:string|null}[];elements:{id:string;projectId:string|null;signature:number}[];pending:unknown[];wallPending:unknown;outcomes:{outcome:string}[];nextRequestId:{epoch:string;sequence:number};capabilities:Record<string,{supported:boolean}>};
type Pixoo={apiVersion:string;identity:{controllerId:string;deviceId:string};configurationRevision:number;generation:number;nextRequestId:string;configuration:{mode:string;filter:{q?:string;provider?:string;projectId?:string;session?:SessionSnapshot['identity']};cadenceMs:number};pendingMode:string|null;sourceConnection:string;participating:boolean;inFlight:number;capabilities:{modes:string[];filters:string[];minimumCadenceMs:number;maximumCadenceMs:number}};
type Device={snapshot?:Snapshot;integration?:Nano|Pixoo;error?:string;received?:number;busy?:boolean};
const age=(ms:number)=>ms<1000?'less than 1s':ms<60000?`${Math.floor(ms/1000)}s`:`${Math.floor(ms/60000)}m`;
const key=(s:SessionSnapshot)=>JSON.stringify(s.identity);
const text=(value:unknown):string=>value===undefined||value===null?'Unknown':typeof value==='object'&&'status' in value&&(value as {status:string}).status==='unknown'?'Unknown':typeof value==='object'?JSON.stringify(value):String(value);
const nano=(value:Nano|Pixoo|undefined):value is Nano=>value?.apiVersion==='nanoleaf.integration/1.0';
const pixoo=(value:Nano|Pixoo|undefined):value is Pixoo=>value?.apiVersion==='pixoo-integration/1.0';
function Badge({children,warning=false}:{children:React.ReactNode;warning?:boolean}){return <span className={'badge'+(warning?' warning':'')}>{children}</span>;}
function Facts({items}:{items:[string,React.ReactNode][]}){return <dl>{items.map(([label,value])=><div key={label}><dt>{label}</dt><dd>{value}</dd></div>)}</dl>;}

type FormProps<T>={title:string;source:T;revision:string;initial:Record<string,string>;disabled?:string;api:Api;path:string;build:(source:T,values:Record<string,string>)=>unknown;refresh:()=>void;children:(values:Record<string,string>,change:(name:string,value:string)=>void)=>React.ReactNode};
function EditForm<T>({title,source,revision,initial,disabled,api,path,build,refresh,children}:FormProps<T>){
 const [values,setValues]=useState(initial),[dirty,setDirty]=useState(false),[status,setStatus]=useState(''),[busy,setBusy]=useState(false),[locked,setLocked]=useState(false);
 const baseline=useRef({source,revision});const initialKey=JSON.stringify(initial);
 useEffect(()=>{if(!dirty){setValues(initial);baseline.current={source,revision};}},[revision,initialKey,dirty]);
 const conflict=dirty&&!locked&&baseline.current.revision!==revision;
 function change(name:string,value:string){if(!dirty)baseline.current={source:structuredClone(source),revision};setDirty(true);setValues(v=>({...v,[name]:value}));}
 async function submit(e:React.FormEvent){e.preventDefault();if(disabled||busy||locked||!dirty||conflict)return;setBusy(true);setStatus('Submitting…');
  try {const result=await api.request<Record<string,unknown>>(path,build(baseline.current.source,values));const outcome=String(result.outcome??'configuration accepted');setStatus(`${outcome}. Physical result is not confirmed.`);setLocked(true);refresh();}
  catch(error){const code=error instanceof ApiError?error.code:'uncertain-result';setStatus(code==='uncertain-result'?'Uncertain result. Do not repeat this command. Refresh observations before starting a new edit.':`Not applied: ${code}. Your edit is retained.`);setLocked(true);refresh();}
  finally{setBusy(false);}
 }
 return <form className="edit" onSubmit={submit}><h3>{title}</h3><fieldset disabled={!!disabled||busy||locked}>{children(values,change)}</fieldset>{disabled&&<p className="hint">Unavailable: {disabled}</p>}{conflict&&<p className="warning">Changed by another client. Your edit is retained. Discard it to load the current values.</p>}<div className="actions"><button disabled={!!disabled||busy||locked||!dirty||conflict} type="submit">Apply {title.toLowerCase()}</button>{dirty&&<button type="button" className="secondary" disabled={busy} onClick={()=>{setDirty(false);setLocked(false);setStatus('');}}>Discard edit / load current</button>}</div><p role="status">{status}</p></form>;
}
function Select({label,value,onChange,options}:{label:string;value:string;onChange:(v:string)=>void;options:{value:string;label:string}[]}){return <label>{label}<select value={value} onChange={e=>onChange(e.target.value)}>{options.map(o=><option key={o.value} value={o.value}>{o.label}</option>)}</select></label>;}
const options=(values:string[])=>values.map(value=>({value,label:value}));
function ComponentView({component,device,context,api,refresh,now,sessions}:{component:Component;device:Device;context:Context;api:Api;refresh:()=>void;now:number;sessions:SessionSnapshot[]}){
 const snapshot=device.snapshot,integr=device.integration;
 const disabled=!context.control?'Your credential is read-only':device.error?'Controller observations are stale':!snapshot?'No controller snapshot':snapshot.state.externalControl.status==='known'&&snapshot.state.externalControl.owner==='external'?'Device is externally controlled':undefined;
 const path=`/api/controllers/v1/${encodeURIComponent(component.id)}`;
 const modes=snapshot?.capabilities.modes;
 const supportedModes=modes?.supported?modes.values.filter(m=>component.kind==='nanoleaf'?['Work','Quiet','Free'].includes(m):component.kind==='pixoo'?['Monitor','Media'].includes(m):false):[];
 const editor=safeEditorUrl(component.editorUrl);
 const elapsed=device.received?Math.max(0,now-device.received):0;
 return <><header className="section-heading"><div><p className="eyebrow">COMPONENT / {component.kind}</p><h2>{component.id}</h2></div><Badge warning={!!device.error}>{device.error?'Stale / unavailable':snapshot?.serviceHealth??'Unknown'}</Badge></header>
 <p className="muted">{component.controllerId} / {component.deviceId}</p>
 <Facts items={[
 ['Selected mode',nano(integr)?integr.mode:pixoo(integr)?integr.configuration.mode:snapshot?.state.desired.mode.status==='known'?snapshot.state.desired.mode.value:'Unknown'],
 ['Desired state',snapshot?`Mode ${snapshot.state.desired.mode.status==='known'?snapshot.state.desired.mode.value:'unknown'} · Power ${snapshot.state.desired.power.status==='known'?(snapshot.state.desired.power.value?'on':'off'):'unknown'} · Brightness ${snapshot.state.desired.brightness.status==='known'?snapshot.state.desired.brightness.value+'%':'unknown'}`:'Unknown'],['Pending changes',snapshot?snapshot.state.pending.length?`${snapshot.state.pending.length} queued: ${snapshot.state.pending.map(p=>p.command.kind).join(', ')}`:'None':'Unknown'],
 ['Last successful transmission',snapshot?.state.lastSuccessfulSend.status==='known'?`Sent ${snapshot.state.lastSuccessfulSend.operationIds.join(', ')} · physical result unknown`:'Unknown'],['Last outcome',snapshot?.state.lastOutcome.status==='known'?`${snapshot.state.lastOutcome.receipt.outcome}${snapshot.state.lastOutcome.receipt.failure?' · '+snapshot.state.lastOutcome.receipt.failure.code:''}`:'Unknown'],
 ['External control',snapshot?.state.externalControl.status==='known'?snapshot.state.externalControl.owner:'Unknown'],['Observation age',snapshot?.state.observation.status==='known'?age(snapshot.state.observation.evidenceAgeMs+elapsed):'Unknown'],
 ['Snapshot fetched',device.received?`${age(elapsed)} ago`:'Never'],['Integration pending',nano(integr)?`${integr.pending.length} commands; wall edits ${integr.wallPending?'pending':'none'}`:pixoo(integr)?integr.pendingMode??'None':'Unknown']
 ]}/>{device.error&&<p role="status" className="warning">{device.error}. Last evidence is retained. Other components remain independent.</p>}
 <h3>Available integration</h3><p>{supportedModes.length?supportedModes.join(' · '):'Mode control unavailable: no supported integration mode declared.'}</p>
 {snapshot&&supportedModes.length>0&&<EditForm title="Mode" source={snapshot} revision={`${snapshot.configurationRevision}:${JSON.stringify(snapshot.generation)}`} initial={{mode:snapshot.state.desired.mode.status==='known'?snapshot.state.desired.mode.value:supportedModes[0]}} disabled={disabled} api={api} path={path+'/commands'} build={(s,v)=>makeCommand(s,{kind:'mode.set',mode:v.mode as Mode})} refresh={refresh}>{(v,c)=><><Select label="Device mode" value={v.mode} onChange={x=>c('mode',x)} options={options(supportedModes)}/><p className="hint">{component.kind==='nanoleaf'?'Work participates; Quiet and Free preserve the owning controller’s policies.':'Monitor presents agent activity. Media opts out; collection continues. This does not start playback.'}</p></>}</EditForm>}
 {nano(integr)&&<>
 <EditForm title="Integration settings" source={integr} revision={integr.revision} initial={{style:integr.settings.style??'classic',coverage:integr.settings.coverage??'whole'}} disabled={disabled??(!integr.capabilities['settings.set']?.supported?'Settings are not supported':undefined)} api={api} path={path+'/integration/commands'} build={(s,v)=>({apiVersion:s.apiVersion,controllerId:s.identity.controllerId,deviceId:s.identity.deviceId,requestId:s.nextRequestId,expectedRevision:s.revision,command:{kind:'settings.set',style:v.style,coverage:v.coverage}})} refresh={refresh}>{(v,c)=><><Select label="Layout style" value={v.style} onChange={x=>c('style',x)} options={options(['classic','project'])}/><Select label="Coverage" value={v.coverage} onChange={x=>c('coverage',x)} options={options(['whole','status'])}/></>}</EditForm>
 <p className="hint">Session source: {integr.source}. Mappings use controller-declared neutral identifiers.</p>
 <NanoMappings integration={integr} disabled={disabled} api={api} path={path} refresh={refresh}/>
 </>}
 {pixoo(integr)&&<EditForm title="Monitor view" source={integr} revision={`${integr.configurationRevision}:${integr.generation}`} initial={{q:integr.configuration.filter.q??'',provider:integr.configuration.filter.provider??'',projectId:integr.configuration.filter.projectId??'',session:integr.configuration.filter.session?JSON.stringify(integr.configuration.filter.session):'',cadence:String(integr.configuration.cadenceMs)}} disabled={disabled} api={api} path={path+'/integration/commands'} build={(s,v)=>({apiVersion:s.apiVersion,controllerId:component.controllerId,deviceId:component.deviceId,requestId:s.nextRequestId,expectedConfigurationRevision:s.configurationRevision,expectedGeneration:s.generation,action:{operation:'view',filter:{...(v.q?{q:v.q}:{}),...(v.provider?{provider:v.provider}:{}),...(v.projectId?{projectId:v.projectId}:{}),...(v.session?{session:JSON.parse(v.session)}:{})},cadenceMs:Number(v.cadence)}})} refresh={refresh}>{(v,c)=><><label>Label / ID filter<input maxLength={120} value={v.q} onChange={e=>c('q',e.target.value)}/></label><Select label="Monitor provider" value={v.provider} onChange={x=>c('provider',x)} options={[{value:'',label:'All providers'},...options(['codex','claude'])]}/><label>Project ID<input maxLength={128} pattern="[A-Za-z0-9_.-]*" value={v.projectId} onChange={e=>c('projectId',e.target.value)}/></label><Select label="Monitor session" value={v.session} onChange={x=>c('session',x)} options={[{value:'',label:'All sessions'},...(v.session&&!sessions.some(s=>JSON.stringify(s.identity)===v.session)?[{value:v.session,label:'Previously selected session'}]:[]),...sessions.map(s=>({value:JSON.stringify(s.identity),label:s.label??s.identity.sessionId}))]}/><label>Update interval (ms)<input type="number" min={integr.capabilities.minimumCadenceMs} max={integr.capabilities.maximumCadenceMs} step="1" value={v.cadence} onChange={e=>c('cadence',e.target.value)}/></label><p className="hint">Filters can produce an empty monitor view. Participation: {integr.participating?'yes':'no'}; source: {integr.sourceConnection}.</p></>}</EditForm>}
 {!nano(integr)&&!pixoo(integr)&&<p className="hint">Settings unavailable: this component has no supported integration extension.</p>}
 <p className="hint">General power, brightness, scenes and media controls are outside this Codex-integration view. Exact previews are not available.</p>{editor?<a href={editor} target="_blank" rel="noopener noreferrer">Open advanced {component.kind==='pixoo'?'playlist':'wall'} editor ↗</a>:<p className="hint">Advanced editor unavailable: no validated link configured.</p>}
 </>;
}
function NanoMappings({integration:s,disabled,api,path,refresh}:{integration:Nano;disabled?:string;api:Api;path:string;refresh:()=>void}){
 const projects=[{value:'',label:'Shared pool'},...s.projects.map(p=>({value:p.id,label:p.id}))];
 const base={source:s,revision:s.revision,api,path:path+'/integration/commands',refresh};
 const command=(state:Nano,cmd:unknown)=>({apiVersion:state.apiVersion,controllerId:state.identity.controllerId,deviceId:state.identity.deviceId,requestId:state.nextRequestId,expectedRevision:state.revision,command:cmd});
 return <><EditForm {...base} title="Element mapping" initial={{element:s.elements[0]?.id??'',project:'',signature:'0'}} disabled={disabled??(!s.elements.length?'No elements declared':!s.capabilities['elements.assign']?.supported?'Element mapping unsupported':undefined)} build={(state,v)=>command(state,{kind:'elements.assign',elements:[{id:v.element,projectId:v.project||null,signature:Number(v.signature)}]})}>{(v,c)=><><Select label="Element" value={v.element} onChange={x=>c('element',x)} options={options(s.elements.map(e=>e.id))}/><Select label="Element project" value={v.project} onChange={x=>c('project',x)} options={projects}/><Select label="Signature" value={v.signature} onChange={x=>c('signature',x)} options={[{value:'0',label:'Off'},{value:'1',label:'On'}]}/><p className="hint">Current: {text(s.elements.find(e=>e.id===v.element))}</p></>}</EditForm>
 <EditForm {...base} title="Task mapping" initial={{task:s.tasks[0]?.id??'',project:''}} disabled={disabled??(!s.tasks.length?'No tasks declared':!s.capabilities['task.assign']?.supported?'Task mapping unsupported':undefined)} build={(state,v)=>command(state,{kind:'task.assign',taskId:v.task,projectId:v.project||null})}>{(v,c)=><><Select label="Task" value={v.task} onChange={x=>c('task',x)} options={options(s.tasks.map(t=>t.id))}/><Select label="Task project" value={v.project} onChange={x=>c('project',x)} options={projects}/><p className="hint">Current: {text(s.tasks.find(t=>t.id===v.task))}</p></>}</EditForm>
 <EditForm {...base} title="Project color" initial={{project:s.projects[0]?.id??'',color:s.projects[0]?.color??'#a9c3ff'}} disabled={disabled??(!s.projects.length?'No projects declared':!s.capabilities['project.color']?.supported?'Project color unsupported':undefined)} build={(state,v)=>command(state,{kind:'project.color',projectId:v.project,color:v.color})}>{(v,c)=><><Select label="Color project" value={v.project} onChange={x=>c('project',x)} options={projects.slice(1)}/><label>Color<input type="color" value={v.color} onChange={e=>c('color',e.target.value)}/></label><p className="hint">Current: {s.projects.find(p=>p.id===v.project)?.color??'Unknown'}</p></>}</EditForm></>;
}
function SessionView({session:s,monitor,context,api,refresh,stale,elapsed}:{session:SessionSnapshot;monitor:Monitor;context:Context;api:Api;refresh:()=>void;stale:boolean;elapsed:number}){
 return <article className="session"><div className="section-heading"><h3>{s.label??s.identity.sessionId}</h3><Badge warning={s.freshness!=='current'||stale}>{stale?'Stale connection':s.freshness}</Badge></div><p className="muted">{s.identity.provider} · {s.identity.client} · {s.identity.hostId} / {s.identity.sourceId}</p>
 <Facts items={[
 ['Activity',s.activity],['Attention',s.attention.length?s.attention.map((a,i)=><span key={i} className="attention">{a.kind==='question'?'Question · continuing':`${a.kind} · blocked attention`} </span>):'None observed'],['Observation age',age(s.observationAgeMs+elapsed)],['Read evidence',s.read],['Parent',s.parent.status==='known'?s.parent.identity.sessionId:s.parent.status==='top-level'?'Top-level session':'Unknown'],['Attributable children',`${s.children.active} active / ${s.children.uncertain} uncertain`]
 ]}/><EditForm title="Label" source={monitor} revision={s.label??''} initial={{label:s.label??''}} disabled={!context.control?'Read-only credential':stale?'Snapshot is stale':undefined} api={api} path="/api/monitor/v1/commands" build={(m,v)=>({operation:'label',requestId:m.nextRequestId,identity:s.identity,label:v.label||null})} refresh={refresh}>{(v,c)=><label>Chosen label<input maxLength={160} value={v.label} placeholder="Choose a label" onChange={e=>c('label',e.target.value)}/></label>}</EditForm>
 {s.notices.length>0&&<h4>Retained notices</h4>}{s.notices.map(n=><div className="notice" key={n.id}><p>{n.kind} · {n.id}</p><p className="hint">Acknowledged by: {n.acknowledgedBy.join(', ')||'none'}. This does not establish success or readership.</p><EditForm title="Monitor acknowledgment" source={monitor} revision={n.id+':'+n.acknowledgedBy.join(',')} initial={{consumer:''}} disabled={!context.control?'Read-only credential':stale?'Snapshot is stale':!context.consumers.length?'No configured consumer':undefined} api={api} path="/api/monitor/v1/commands" build={(m,v)=>({operation:'acknowledge',requestId:m.nextRequestId,identity:s.identity,noticeId:n.id,consumerId:v.consumer})} refresh={refresh}>{(v,c)=><Select label="Acknowledge for" value={v.consumer} onChange={x=>c('consumer',x)} options={[{value:'',label:'Choose a consumer'},...context.consumers.filter(x=>!n.acknowledgedBy.includes(x)).map(x=>({value:x,label:x}))]}/>}</EditForm></div>)}
 </article>;
}
function Dashboard({api,disconnect}:{api:Api;disconnect:()=>void}){
 const [context,setContext]=useState<Context>(),[monitor,setMonitor]=useState<Monitor>(),[devices,setDevices]=useState<Record<string,Device>>({}),[view,setView]=useState('activity'),[q,setQ]=useState(''),[provider,setProvider]=useState(''),[error,setError]=useState(''),[feed,setFeed]=useState(false),[now,setNow]=useState(Date.now()),[received,setReceived]=useState(0);
 const refreshRef=useRef<()=>void>(()=>{}),deviceRefresh=useRef<(id:string)=>void>(()=>{});
 useEffect(()=>{
  const stop=new AbortController();let busy=false,again=false;const deviceBusy=new Set<string>();let current:Context|undefined;
  const update=(id:string,value:Partial<Device>)=>{if(!stop.signal.aborted)setDevices(old=>({...old,[id]:{...old[id],...value}}));};
  async function refreshDevice(c:Component){if(deviceBusy.has(c.id)||stop.signal.aborted)return;deviceBusy.add(c.id);
   try {const snapshot=await api.request<Snapshot>(`/api/controllers/v1/${c.id}/snapshot`,undefined,stop.signal);let integration:Nano|Pixoo|undefined;
    if(['nanoleaf','pixoo'].includes(c.kind))integration=await api.request<Nano|Pixoo>(`/api/controllers/v1/${c.id}/integration/snapshot`,undefined,stop.signal);
    update(c.id,{snapshot,integration,error:undefined,received:Date.now()});
   }catch(e){update(c.id,{error:e instanceof ApiError?e.code:'unavailable'});}finally{deviceBusy.delete(c.id);}
  }
  async function refresh(){if(busy){again=true;return;}busy=true;
   try {const ctx=await api.request<Context>('/api/dashboard/v1/context',undefined,stop.signal);const next=await api.request<Monitor>('/api/monitor/v1/sessions',undefined,stop.signal);if(stop.signal.aborted)return;current=ctx;setContext(ctx);setMonitor(old=>old&&old.ownerId===next.ownerId&&old.snapshot.revision>next.snapshot.revision?old:next);setReceived(Date.now());setError('');}
   catch(e){if(!stop.signal.aborted)setError(e instanceof ApiError?e.code:'unavailable');}finally{busy=false;if(again&&!stop.signal.aborted){again=false;void refresh();}}
  }
  refreshRef.current=()=>void refresh();deviceRefresh.current=id=>{const c=current?.components.find(c=>c.id===id);if(c)void refreshDevice(c);};
  void refresh().then(()=>current?.components.forEach(c=>void refreshDevice(c)));
  void api.feed(stop.signal,()=>void refresh(),value=>{if(!stop.signal.aborted)setFeed(value);});
  const interval=setInterval(()=>{void refresh();current?.components.forEach(c=>void refreshDevice(c));},5000),clock=setInterval(()=>setNow(Date.now()),1000);
  return ()=>{stop.abort();clearInterval(interval);clearInterval(clock);};
 },[api]);
 const sessions=monitor?.snapshot.sessions??[],filtered=sessions.filter(s=>(!provider||s.identity.provider===provider)&&(!q||(s.label??s.identity.sessionId).toLowerCase().includes(q.toLowerCase())));
 return <div className="shell"><a className="skip" href="#main">Skip to content</a><aside><div className="brand"><span className="rabbit">◈</span><div>BUNNY<small>LOCAL INTEGRATION</small></div></div><nav aria-label="Main navigation"><button aria-current={view==='activity'?'page':undefined} onClick={()=>setView('activity')}>Activity <span>{sessions.length}</span></button><p className="nav-label">COMPONENTS</p>{context?.components.map(c=><button key={c.id} aria-current={view===c.id?'page':undefined} onClick={()=>setView(c.id)}>{c.id}<small>{c.kind}</small></button>)}<button aria-current={view==='connections'?'page':undefined} onClick={()=>setView('connections')}>Connections</button></nav><div className="sidebar-foot"><Badge warning={!feed||!!error}>{error?'Connection stale':feed?'Feed connected':'Reconnecting'}</Badge><p>Inspection sends no device commands.</p><button className="secondary" onClick={disconnect}>Disconnect</button></div></aside><main id="main" tabIndex={-1} data-revision={monitor?.snapshot.revision}><header className="top"><span>YOUR WORKSPACE / INTEGRATION</span><span>{context?.control?'Control enabled':'Read only'} · Local</span></header>
 <section hidden={view!=='activity'}><header className="hero"><p className="eyebrow">CODEX & CONNECTED COMPONENTS</p><h1>Your work, at a glance.</h1><p>Activity, attention and device participation. Every action stays explicit.</p></header><div className="stats"><div><strong>{sessions.filter(s=>s.activity==='active').length}</strong><span>Active sessions</span></div><div><strong>{sessions.reduce((n,s)=>n+s.attention.length,0)}</strong><span>Attention signals</span></div><div><strong>{context?.components.length??0}</strong><span>Components</span></div><div><strong>{monitor?.snapshot.collector??'Unknown'}</strong><span>Collector health</span></div></div><div className="filters"><label>Find a session<input type="search" maxLength={120} value={q} onChange={e=>setQ(e.target.value)} placeholder="Chosen label or session ID"/></label><Select label="Provider" value={provider} onChange={setProvider} options={[{value:'',label:'All providers'},...options(['codex','claude'])]}/></div>{error&&<p role="alert" className="warning">{error}. Last observations are stale; edits are disabled.</p>}{!filtered.length&&<div className="empty"><h2>{q||provider?'No matching sessions':'No sessions observed'}</h2><p>{q||provider?'Change the filters to see other observations.':'Component status and supported integration controls remain available.'}</p></div>}<div className="sessions">{sessions.map(s=><div key={key(s)} hidden={!filtered.includes(s)}><SessionView session={s} monitor={monitor!} context={context!} api={api} refresh={()=>refreshRef.current()} stale={!!error||!received||now-received>10000} elapsed={Math.max(0,now-received)} /></div>)}</div></section>
 {context?.components.map(c=><section key={c.id} hidden={view!==c.id}><ComponentView component={c} device={devices[c.id]??{}} context={{...context,control:context.control&&!error}} api={api} refresh={()=>deviceRefresh.current(c.id)} now={now} sessions={sessions}/></section>)}
 <section hidden={view!=='connections'}><header className="hero"><p className="eyebrow">SOURCES & CONNECTIONS</p><h1>Evidence, not assumptions.</h1></header><Facts items={[
 ['Collector',monitor?.snapshot.collector??'Unknown'],['State owner',monitor?.ownerId??'Unknown'],['Feed',feed?'Connected':'Reconnecting'],['Snapshot age',received?age(now-received):'Unknown'],['Lost observations',monitor?.snapshot.lossCount??'Unknown'],['Connection error',error||'None observed']
 ]}/><h2>Observed sources</h2>{[...new Set(sessions.map(s=>`${s.identity.provider} / ${s.identity.hostId} / ${s.identity.sourceId}`))].map(s=><p key={s}>{s}</p>)}{!sessions.length&&<p>No source evidence yet.</p>}<p className="hint">A connected collector does not prove a fresh session, successful task, read chat or physical device result.</p></section><footer>BUNNY / Source observations and deliberate controls</footer></main></div>;
}
function App(){const [api,setApi]=useState<Api>(),[token,setToken]=useState('');return api?<Dashboard api={api} disconnect={()=>{setApi(undefined);setToken('');}}/>:<main className="login"><p className="eyebrow">BUNNY / LOCAL INTEGRATION</p><h1>Your workspace.<br/>One clear view.</h1><p>Connect to inspect agent activity and supported component integration.</p><form onSubmit={e=>{e.preventDefault();if(/^[A-Za-z0-9_-]{43}$/.test(token)){setApi(new Api(token));setToken('');}}}><label>Hub browser access token<input type="password" autoComplete="off" required pattern="[A-Za-z0-9_-]{43}" value={token} onChange={e=>setToken(e.target.value)}/></label><button>Connect</button></form><p className="hint">Use a separately provisioned hub credential, never a native controller token. It stays in this page's memory and is cleared on disconnect or reload.</p></main>;}
createRoot(document.getElementById('root')!).render(<App/>);
