import React, {useEffect,useId,useRef,useState} from 'react';
import {createRoot} from 'react-dom/client';
import type {Snapshot as StateSnapshot,SessionSnapshot} from '../../../packages/agent-state/src/types';
import type {Snapshot,Mode,Command,MediaAction} from '../../../packages/contracts/src/types';
import {Api,ApiError,failureMessage,receiptEvidence,type ReceiptEvidence,makeCommand,safeEditorUrl,generalReasons,brightnessDraft,sceneOptions,nanoleafContentReason,type GeneralReasons,type Context,type Component} from './client';
import './style.css';

type Monitor={snapshot:StateSnapshot;nextRequestId:string;ownerId:string};
type Nano={apiVersion:string;identity:Snapshot['identity'];revision:string;configurationRevision:number;mode:string;settings:{style?:string;coverage?:string};source:string;projects:{id:string;color:string}[];tasks:{id:string;projectId:string|null;overrideProjectId:string|null}[];elements:{id:string;projectId:string|null;signature:number}[];pending:unknown[];wallPending:unknown;outcomes:{requestId:{epoch:string;sequence:number};outcome:string;failure?:{code:string}}[];nextRequestId:{epoch:string;sequence:number};scenes?:{id:string;name?:string}[];capabilities:Record<string,{supported:boolean}>};
type Pixoo={apiVersion:string;identity:{controllerId:string;deviceId:string};configurationRevision:number;generation:number;nextRequestId:string;configuration:{mode:string;filter:{q?:string;provider?:string;projectId?:string;session?:SessionSnapshot['identity']};cadenceMs:number};pendingMode:string|null;sourceConnection:string;participating:boolean;inFlight:number;lastOutcome:null|{status:string;code?:string};capabilities:{modes:string[];filters:string[];minimumCadenceMs:number;maximumCadenceMs:number}};
type Device={snapshot?:Snapshot;integration?:Nano|Pixoo;error?:string;received?:number;busy?:boolean};
const age=(ms:number)=>ms<1000?'less than 1s':ms<60000?`${Math.floor(ms/1000)}s`:`${Math.floor(ms/60000)}m`;
const key=(s:SessionSnapshot)=>JSON.stringify(s.identity);
const text=(value:unknown):string=>value===undefined||value===null?'Unknown':typeof value==='object'&&'status' in value&&(value as {status:string}).status==='unknown'?'Unknown':typeof value==='object'?JSON.stringify(value):String(value);
const nano=(value:Nano|Pixoo|undefined):value is Nano=>value?.apiVersion==='nanoleaf.integration/1.0';
const pixoo=(value:Nano|Pixoo|undefined):value is Pixoo=>value?.apiVersion==='pixoo-integration/1.0';
const title=(value:string)=>value.charAt(0).toUpperCase()+value.slice(1);
/** The Pixoo integration envelope. Mode and view changes share the extension's ticket, revision and generation guards. */
const pixooRequest=(s:Pixoo,component:Component,action:unknown)=>({apiVersion:s.apiVersion,controllerId:component.controllerId,deviceId:component.deviceId,requestId:s.nextRequestId,expectedConfigurationRevision:s.configurationRevision,expectedGeneration:s.generation,action});
type ObservedReceipt=ReceiptEvidence&{requestId:unknown;outcome:string;failure?:{code:string}};
/** A later snapshot can carry the terminal outcome for a submitted ticket; queued receipts are not terminal. */
function observedResult(source:unknown,ticket:unknown):string|undefined{
 if(ticket===undefined||!source||typeof source!=='object')return;
 const observed=source as {outcomes?:ObservedReceipt[];state?:{lastOutcome?:{status:string;receipt?:ObservedReceipt}}};
 const records=[...(observed.outcomes??[]),...(observed.state?.lastOutcome?.status==='known'&&observed.state.lastOutcome.receipt?[observed.state.lastOutcome.receipt]:[])];
 const result=records.find(r=>JSON.stringify(r.requestId)===JSON.stringify(ticket));
 if(result&&result.outcome!=='queued')return `Result updated: ${result.outcome}${result.failure?' · '+result.failure.code:''}.${result.priorEffects!==undefined?' '+receiptEvidence(result):''} Physical result is not confirmed.`;
}
/** Disabling the focused control while a command runs would drop keyboard focus to the document. Once the command settles, focus returns to that control, or to the first enabled control of the same group when it is locked or gone. */
function useRestoredFocus(active:boolean){
 const saved=useRef<{control:HTMLElement;group:HTMLElement|null}|null>(null);
 useEffect(()=>{
  if(active||!saved.current)return;
  const {control,group}=saved.current;saved.current=null;
  if(document.activeElement!==document.body)return;
  if(control.isConnected&&!control.matches(':disabled')){control.focus();return;}
  if(group?.isConnected)group.querySelector<HTMLElement>('button:not(:disabled),select:not(:disabled),input:not(:disabled)')?.focus();
 },[active]);
 return ()=>{const control=document.activeElement;if(control instanceof HTMLElement&&control!==document.body)saved.current={control,group:control.closest<HTMLElement>('.edit')};};
}
/** One-click commands use the latest observed snapshot at activation and stay busy until the refreshed snapshot arrives, so the next activation carries fresh guards. Only an accepted ticket is watched for its terminal outcome; a rejected ticket may be consumed by another client. An uncertain result locks the group until the user loads current values. */
function useCommand(api:Api,path:string,refresh:()=>void|Promise<void>,source:unknown){
 const [status,setStatus]=useState(''),[busy,setBusy]=useState(false),[locked,setLocked]=useState(false),[submitted,setSubmitted]=useState<{label:string;ticket:unknown}>();
 const keepFocus=useRestoredFocus(busy);
 useEffect(()=>{const message=submitted&&observedResult(source,submitted.ticket);if(message)setStatus(`${submitted.label}: ${message}`);},[source,submitted]);
 async function run(label:string,request:unknown){if(busy||locked)return;keepFocus();setBusy(true);setStatus(`${label}: submitting…`);setSubmitted(undefined);
  try {const result=await api.request<Record<string,unknown>>(path,request);const failure=result.failure&&typeof result.failure==='object'&&'code' in result.failure?' · '+String((result.failure as {code:unknown}).code):'';setStatus(`${label}: ${String(result.outcome??'configuration accepted')}${failure}. Physical result is not confirmed.`);if(!failure)setSubmitted({label,ticket:(request as {requestId?:unknown}).requestId});}
  catch(error){const result=failureMessage(error);setStatus(`${label}: ${result.message}`);setLocked(result.locked);}
  finally{await refresh();setBusy(false);}
 }
 return {status,busy,locked,run,unlock:()=>{setLocked(false);setStatus('');setSubmitted(undefined);void refresh();}};
}
function Badge({children,warning=false}:{children:React.ReactNode;warning?:boolean}){return <span className={'badge'+(warning?' warning':'')}>{children}</span>;}
function Facts({items}:{items:[string,React.ReactNode][]}){return <dl>{items.map(([label,value])=><div key={label}><dt>{label}</dt><dd>{value}</dd></div>)}</dl>;}

type FormProps<T>={title:string;source:T;revision:string;initial:Record<string,string>;disabled?:string;api:Api;path:string;build:(source:T,values:Record<string,string>)=>unknown;refresh:()=>void|Promise<void>;submitLabel?:string;children:(values:Record<string,string>,change:(name:string,value:string)=>void)=>React.ReactNode};
function EditForm<T>({title,source,revision,initial,disabled,api,path,build,refresh,submitLabel,children}:FormProps<T>){
 const heading=useId();
 const [draft,setDraft]=useState<{values:Record<string,string>;source:T;revision:string}|null>(null),[status,setStatus]=useState(''),[busy,setBusy]=useState(false),[locked,setLocked]=useState(false);
 const keepFocus=useRestoredFocus(busy);
 const values=draft?.values??initial,dirty=draft!==null;
 const conflict=dirty&&!locked&&draft.revision!==revision;
 useEffect(()=>{
  if(!draft||!locked)return;
  const message=observedResult(source,(draft.source as {nextRequestId?:unknown}).nextRequestId);
  if(message)setStatus(message);
 },[source,draft,locked]);
 function change(name:string,value:string){setDraft(old=>old?{...old,values:{...old.values,[name]:value}}:{source:structuredClone(source),revision,values:{...initial,[name]:value}});}
 async function submit(e:React.FormEvent){e.preventDefault();if(disabled||busy||locked||!dirty||conflict)return;keepFocus();setBusy(true);setStatus('Submitting…');
  try {const result=await api.request<Record<string,unknown>>(path,build(draft!.source,values));const outcome=String(result.outcome??'configuration accepted');setStatus(`${outcome}${result.failure&&typeof result.failure==='object'&&'code' in result.failure?' · '+String(result.failure.code):''}. Physical result is not confirmed.`);setLocked(true);void refresh();}
  catch(error){const result=failureMessage(error);setStatus(result.message);setLocked(result.locked);void refresh();}
  finally{setBusy(false);}
 }
 return <form className="edit" aria-labelledby={heading} onSubmit={submit}><h3 id={heading}>{title}</h3><fieldset disabled={!!disabled||busy||locked}>{children(values,change)}</fieldset>{disabled&&<p className="hint">Unavailable: {disabled}</p>}{conflict&&<p className="warning">Changed by another client. Your edit is retained. Discard it to load the current values.</p>}<div className="actions"><button disabled={!!disabled||busy||locked||!dirty||conflict} type="submit">{submitLabel??`Apply ${title.toLowerCase()}`}</button>{dirty&&<button type="button" className="secondary" disabled={busy} onClick={()=>{setDraft(null);setLocked(false);setStatus('');}}>Discard edit / load current</button>}</div><p role="status">{status}</p></form>;
}
function Select({label,value,onChange,options}:{label:string;value:string;onChange:(v:string)=>void;options:{value:string;label:string}[]}){return <label>{label}<select value={value} onChange={e=>onChange(e.target.value)}>{options.map(o=><option key={o.value} value={o.value}>{o.label}</option>)}</select></label>;}
const options=(values:string[])=>values.map(value=>({value,label:value}));
function ComponentView({component,device,context,api,refresh,now,sessions}:{component:Component;device:Device;context:Context;api:Api;refresh:()=>void|Promise<void>;now:number;sessions:SessionSnapshot[]}){
 const snapshot=device.snapshot,integr=device.integration;
 const disabled=!context.control?'Your credential is read-only':device.error?'Controller observations are stale':!snapshot?'No controller snapshot':snapshot.state.externalControl.status==='known'&&snapshot.state.externalControl.owner==='external'?'Device is externally controlled':undefined;
 const path=`/api/controllers/v1/${encodeURIComponent(component.id)}`;
 const modes=snapshot?.capabilities.modes;
 const supportedModes=modes?.supported?modes.values.filter(m=>component.kind==='nanoleaf'?['Work','Quiet','Free'].includes(m):component.kind==='pixoo'?['Monitor','Media'].includes(m):false):[];
 const editor=safeEditorUrl(component.editorUrl);
 const elapsed=device.received?Math.max(0,now-device.received):0;
 // Pixoo presents agent status in Monitor. Content controls wait for the observed Media mode; nothing switches or restores on its own.
 const pixooMode=pixoo(integr)?{mode:integr.configuration.mode,pending:integr.pendingMode}:undefined;
 // Nanoleaf presents agent status in Work and Quiet. Scenes wait for the observed Free mode from the same controller v1 snapshot that guards the scene command.
 const content=pixooMode?(pixooMode.pending?`Pixoo is switching to ${title(pixooMode.pending)}; wait for the observed mode`:pixooMode.mode!=='media'?'Pixoo is in Monitor and presents agent status; playlist and playback controls need Media':undefined):component.kind==='nanoleaf'&&snapshot?nanoleafContentReason(snapshot):undefined;
 const reasons=generalReasons({snapshot,control:context.control,common:device.error?'Controller observations are stale':snapshot?.state.externalControl.status==='known'&&snapshot.state.externalControl.owner==='external'?'Device is externally controlled':undefined,content});
 const switchCommand=useCommand(api,path+'/integration/commands',refresh,integr);
 const freeCommand=useCommand(api,path+'/commands',refresh,snapshot);
 const switchToFree=component.kind==='nanoleaf'&&snapshot&&supportedModes.includes('Free')&&snapshot.state.desired.mode.status==='known'&&snapshot.state.desired.mode.value!=='Free'&&!snapshot.state.pending.some(p=>p.command.kind==='mode.set')?<div className="switch"><div className="actions"><button type="button" disabled={!!disabled||freeCommand.busy||freeCommand.locked} onClick={()=>void freeCommand.run('Switch to Free',makeCommand(snapshot,{kind:'mode.set',mode:'Free'}))}>Switch to Free</button>{freeCommand.locked&&<button type="button" className="secondary" onClick={freeCommand.unlock}>Load current / unlock</button>}</div><p className="hint">One explicit controller v1 mode command through the existing mode control. Returning to Work or Quiet uses the same control.{disabled?` Unavailable: ${disabled}`:''}</p><p role="status">{freeCommand.status}</p></div>:undefined;
 const switchToMedia=pixoo(integr)&&pixooMode&&pixooMode.mode!=='media'&&!pixooMode.pending?<div className="switch"><div className="actions"><button type="button" disabled={!!disabled||switchCommand.busy||switchCommand.locked} onClick={()=>void switchCommand.run('Switch to Media',pixooRequest(integr,component,{operation:'mode',mode:'media'}))}>Switch to Media</button>{switchCommand.locked&&<button type="button" className="secondary" onClick={switchCommand.unlock}>Load current / unlock</button>}</div><p className="hint">One explicit mode command through the existing mode control. Returning to Monitor uses the same control.{disabled?` Unavailable: ${disabled}`:''}</p><p role="status">{switchCommand.status}</p></div>:undefined;
 return <><header className="section-heading"><div><p className="eyebrow">COMPONENT / {component.kind}</p><h2>{component.id}</h2></div><Badge warning={!!device.error}>{device.error?'Stale / unavailable':snapshot?.serviceHealth??'Unknown'}</Badge></header>
 <p className="muted">{component.controllerId} / {component.deviceId}</p>
 <Facts items={[
 ['Selected mode',nano(integr)?integr.mode:pixooMode?`${title(pixooMode.mode)}${pixooMode.pending?` (switching to ${title(pixooMode.pending)})`:''}`:snapshot?.state.desired.mode.status==='known'?snapshot.state.desired.mode.value:'Unknown'],
 ['Desired state',snapshot?`Mode ${snapshot.state.desired.mode.status==='known'?snapshot.state.desired.mode.value:'unknown'} · Power ${snapshot.state.desired.power.status==='known'?(snapshot.state.desired.power.value?'on':'off'):'unknown'} · Brightness ${snapshot.state.desired.brightness.status==='known'?snapshot.state.desired.brightness.value+'%':'unknown'}`:'Unknown'],['Pending changes',snapshot?snapshot.state.pending.length?`${snapshot.state.pending.length} queued: ${snapshot.state.pending.map(p=>p.command.kind).join(', ')}`:'None':'Unknown'],
 ['Last successful transmission',snapshot?.state.lastSuccessfulSend.status==='known'?`Sent ${snapshot.state.lastSuccessfulSend.operationIds.join(', ')} · physical result unknown`:'Unknown'],['Last outcome',snapshot?.state.lastOutcome.status==='known'?`${snapshot.state.lastOutcome.receipt.outcome}${snapshot.state.lastOutcome.receipt.failure?' · '+snapshot.state.lastOutcome.receipt.failure.code:''}`:'Unknown'],
 ['External control',snapshot?.state.externalControl.status==='known'?snapshot.state.externalControl.owner:'Unknown'],['Observation age',snapshot?.state.observation.status==='known'?age(snapshot.state.observation.evidenceAgeMs+elapsed):'Unknown'],
 ['Snapshot fetched',device.received?`${age(elapsed)} ago`:'Never'],['Integration outcomes',nano(integr)?integr.outcomes.length?integr.outcomes.map(r=>`${r.outcome}${r.failure?' · '+r.failure.code:''}`).join('; '):'None recorded':pixoo(integr)?integr.lastOutcome?`${integr.lastOutcome.status}${integr.lastOutcome.code?' · '+integr.lastOutcome.code:''}`:'None recorded':'Unknown'],['Integration pending',nano(integr)?`${integr.pending.length} commands; wall edits ${integr.wallPending?'pending':'none'}`:pixoo(integr)?integr.pendingMode??'None':'Unknown']
 ]}/>{device.error&&<p role="status" className="warning">{device.error}. Last evidence is retained. Other components remain independent.</p>}
 <h3>Available integration</h3><p>{pixoo(integr)?integr.capabilities.modes.map(title).join(' · '):supportedModes.length?supportedModes.join(' · '):'Mode control unavailable: no supported integration mode declared.'}</p>
 {pixoo(integr)&&<EditForm title="Mode" source={integr} revision={`${integr.configurationRevision}:${integr.generation}`} initial={{mode:integr.configuration.mode}} disabled={disabled} api={api} path={path+'/integration/commands'} build={(s,v)=>pixooRequest(s,component,{operation:'mode',mode:v.mode})} refresh={refresh}>{(v,c)=><><Select label="Device mode" value={v.mode} onChange={x=>c('mode',x)} options={integr.capabilities.modes.map(m=>({value:m,label:title(m)}))}/><p className="hint">Monitor presents agent activity. Media opts out; collection continues. This does not start playback. Pending mode: {integr.pendingMode?title(integr.pendingMode):'none'}.</p></>}</EditForm>}
 {snapshot&&supportedModes.length>0&&!pixoo(integr)&&<EditForm title="Mode" source={snapshot} revision={`${snapshot.configurationRevision}:${JSON.stringify(snapshot.generation)}`} initial={{mode:snapshot.state.desired.mode.status==='known'?snapshot.state.desired.mode.value:supportedModes[0]}} disabled={disabled} api={api} path={path+'/commands'} build={(s,v)=>makeCommand(s,{kind:'mode.set',mode:v.mode as Mode})} refresh={refresh}>{(v,c)=><><Select label="Device mode" value={v.mode} onChange={x=>c('mode',x)} options={options(supportedModes)}/><p className="hint">{component.kind==='nanoleaf'?'Work participates; Quiet and Free preserve the owning controller’s policies.':'Monitor presents agent activity. Media opts out; collection continues. This does not start playback.'}</p></>}</EditForm>}
 {nano(integr)&&<>
 <EditForm title="Integration settings" source={integr} revision={integr.revision} initial={{style:integr.settings.style??'classic',coverage:integr.settings.coverage??'whole'}} disabled={disabled??(!integr.capabilities['settings.set']?.supported?'Settings are not supported':undefined)} api={api} path={path+'/integration/commands'} build={(s,v)=>({apiVersion:s.apiVersion,controllerId:s.identity.controllerId,deviceId:s.identity.deviceId,requestId:s.nextRequestId,expectedRevision:s.revision,command:{kind:'settings.set',style:v.style,coverage:v.coverage}})} refresh={refresh}>{(v,c)=><><Select label="Layout style" value={v.style} onChange={x=>c('style',x)} options={options(['classic','project'])}/><Select label="Coverage" value={v.coverage} onChange={x=>c('coverage',x)} options={options(['whole','status'])}/></>}</EditForm>
 <p className="hint">Session source: {integr.source}. Mappings use controller-declared neutral identifiers.</p>
 <NanoMappings integration={integr} disabled={disabled} api={api} path={path} refresh={refresh}/>
 </>}
 {pixoo(integr)&&<EditForm title="Monitor view" source={integr} revision={`${integr.configurationRevision}:${integr.generation}`} initial={{q:integr.configuration.filter.q??'',provider:integr.configuration.filter.provider??'',projectId:integr.configuration.filter.projectId??'',session:integr.configuration.filter.session?JSON.stringify(integr.configuration.filter.session):'',cadence:String(integr.configuration.cadenceMs)}} disabled={disabled} api={api} path={path+'/integration/commands'} build={(s,v)=>({apiVersion:s.apiVersion,controllerId:component.controllerId,deviceId:component.deviceId,requestId:s.nextRequestId,expectedConfigurationRevision:s.configurationRevision,expectedGeneration:s.generation,action:{operation:'view',filter:{...(v.q?{q:v.q}:{}),...(v.provider?{provider:v.provider}:{}),...(v.projectId?{projectId:v.projectId}:{}),...(v.session?{session:JSON.parse(v.session)}:{})},cadenceMs:Number(v.cadence)}})} refresh={refresh}>{(v,c)=><><label>Label / ID filter<input maxLength={120} value={v.q} onChange={e=>c('q',e.target.value)}/></label><Select label="Monitor provider" value={v.provider} onChange={x=>c('provider',x)} options={[{value:'',label:'All providers'},...options(['codex','claude'])]}/><label>Project ID<input maxLength={128} pattern="[A-Za-z0-9_.-]*" value={v.projectId} onChange={e=>c('projectId',e.target.value)}/></label><Select label="Monitor session" value={v.session} onChange={x=>c('session',x)} options={[{value:'',label:'All sessions'},...(v.session&&!sessions.some(s=>JSON.stringify(s.identity)===v.session)?[{value:v.session,label:'Previously selected session'}]:[]),...sessions.map(s=>({value:JSON.stringify(s.identity),label:s.label??s.identity.sessionId}))]}/><label>Update interval (ms)<input type="number" min={integr.capabilities.minimumCadenceMs} max={integr.capabilities.maximumCadenceMs} step="1" value={v.cadence} onChange={e=>c('cadence',e.target.value)}/></label><p className="hint">Filters can produce an empty monitor view. Participation: {integr.participating?'yes':'no'}; source: {integr.sourceConnection}.</p></>}</EditForm>}
 {!nano(integr)&&!pixoo(integr)&&<p className="hint">Settings unavailable: this component has no supported integration extension.</p>}
 <p className="eyebrow general">GENERAL CONTROLS</p>
 {snapshot?<GeneralControls component={component} snapshot={snapshot} integration={integr} reasons={reasons} api={api} path={path+'/commands'} refresh={refresh} mediaExtra={switchToMedia} sceneExtra={switchToFree}/>:<p className="hint">General controls unavailable: no controller snapshot.</p>}
 <p className="hint">Rendition selection is not part of this view. Exact previews are not available.</p>{editor?<a href={editor} target="_blank" rel="noopener noreferrer">Open advanced {component.kind==='pixoo'?'playlist':'wall'} editor ↗</a>:<p className="hint">Advanced editor unavailable: no validated link configured.</p>}
 </>;
}
const actionLabels:Record<string,string>={pause:'Pause',resume:'Resume',stop:'Stop',next:'Next',previous:'Previous',clear:'Clear','restart-with-changes':'Restart with changes'};
/** Capability-driven general controls. Each control submits one guarded controller v1 command; a disabled control names its reason. */
function GeneralControls({component,snapshot,integration,reasons,api,path,refresh,mediaExtra,sceneExtra}:{component:Component;snapshot:Snapshot;integration:Nano|Pixoo|undefined;reasons:GeneralReasons;api:Api;path:string;refresh:()=>void|Promise<void>;mediaExtra?:React.ReactNode;sceneExtra?:React.ReactNode}){
 const revision=`${snapshot.configurationRevision}:${JSON.stringify(snapshot.generation)}`,pixel=component.kind==='pixoo';
 const brightness=snapshot.capabilities.brightness,range=brightness.supported?brightness:{minimum:0,maximum:100},draft=brightnessDraft(snapshot);
 const power=pixel?'Screen power':'Power',wall=component.kind==='nanoleaf';
 const override=snapshot.state.desired.brightness;
 return <>
 <EditForm title={power} source={snapshot} revision={revision} initial={{on:snapshot.state.desired.power.status==='known'?(snapshot.state.desired.power.value?'on':'off'):'on'}} disabled={reasons.power} api={api} path={path} build={(s,v)=>makeCommand(s,{kind:'power.set',on:v.on==='on'})} refresh={refresh}>{(v,c)=><><Select label={power} value={v.on} onChange={x=>c('on',x)} options={[{value:'on',label:'On'},{value:'off',label:'Off'}]}/><p className="hint">{pixel?'Screen off pauses playback; screen on does not resume it. Power works in Monitor and Media and does not change the mode.':wall?'Power works in Work, Quiet and Free and does not change the mode. While off, the wall keeps tracking tasks and writes nothing until the next explicit mode command.':'Power does not change the device mode.'}</p></>}</EditForm>
 <EditForm title="Brightness" source={snapshot} revision={revision} initial={{percent:String(draft.value)}} disabled={reasons.brightness} api={api} path={path} build={(s,v)=>makeCommand(s,{kind:'brightness.set',percent:Number(v.percent)})} refresh={refresh}>{(v,c)=><><label>Brightness (%)<input type="range" min={range.minimum} max={range.maximum} step={1} value={v.percent} onChange={e=>c('percent',e.target.value)}/></label><p className="hint">Selected {v.percent}% of {range.minimum}–{range.maximum}. {wall?(override.status==='known'?`Brightness override active: ${override.value}% until the next explicit mode command, which reapplies that mode’s brightness policy.`:'No brightness override is active; the wall uses its mode’s brightness policy and the slider starts at a placeholder, not an observed value.'):draft.source==='unknown'?'Current brightness is unknown; the slider starts at a placeholder, not an observed value.':`Current ${draft.source} brightness is ${draft.value}%.`} Brightness works in every mode and does not change the mode.</p></>}</EditForm>
 <MediaControls snapshot={snapshot} reason={reasons.media} api={api} path={path} refresh={refresh} extra={mediaExtra}/>
 <SceneControls snapshot={snapshot} integration={integration} reason={reasons.scenes} api={api} path={path} refresh={refresh} extra={sceneExtra}/>
 </>;
}
/** Saved scenes are one-click actions with a parameter: the controller-declared ID list, labelled by user-chosen names when the integration supplies them. One guarded scene command; the mode never changes as a side effect. */
function SceneControls({snapshot,integration,reason,api,path,refresh,extra}:{snapshot:Snapshot;integration:Nano|Pixoo|undefined;reason?:string;api:Api;path:string;refresh:()=>void|Promise<void>;extra?:React.ReactNode}){
 const heading=useId();
 const scenes=sceneOptions(snapshot,nano(integration)?integration:undefined);
 const [sceneId,setSceneId]=useState('');const selected=scenes.some(s=>s.value===sceneId)?sceneId:scenes[0]?.value??'';
 const command=useCommand(api,path,refresh,snapshot);
 const disabled=reason??(!scenes.length?'No saved scenes are discovered by this controller':undefined);
 return <div className="edit" role="group" aria-labelledby={heading}><h3 id={heading}>Scenes</h3><fieldset disabled={!!disabled||command.busy||command.locked}><Select label="Saved scene" value={selected} onChange={setSceneId} options={scenes.length?scenes:[{value:'',label:'No saved scenes discovered'}]}/><p className="hint">Scenes come from the controller’s discovery; names are the user-chosen Nanoleaf app names when supplied, IDs otherwise. Activating a scene is one write in Free and does not change the mode.</p><div className="actions"><button type="button" disabled={!selected} onClick={()=>void command.run('Activate scene',makeCommand(snapshot,{kind:'scene.activate',sceneId:selected}))}>Activate scene</button></div></fieldset>{disabled&&<p className="hint">Unavailable: {disabled}</p>}{extra}{command.locked&&<div className="actions"><button type="button" className="secondary" onClick={command.unlock}>Load current / unlock</button></div>}<p role="status">{command.status}</p></div>;
}
function MediaControls({snapshot,reason,api,path,refresh,extra}:{snapshot:Snapshot;reason?:string;api:Api;path:string;refresh:()=>void|Promise<void>;extra?:React.ReactNode}){
 const heading=useId();
 const media=snapshot.capabilities.media,playlists=media.supported?media.playlistIds:[],actions:MediaAction[]=media.supported?media.actions:[];
 const [playlistId,setPlaylistId]=useState('');const selected=playlists.includes(playlistId)?playlistId:playlists[0]??'';
 const command=useCommand(api,path,refresh,snapshot);
 const disabled=reason??(!playlists.length&&!actions.length?'No playlists or playback actions are declared':undefined);
 const run=(label:string,cmd:Command)=>void command.run(label,makeCommand(snapshot,cmd));
 return <div className="edit" role="group" aria-labelledby={heading}><h3 id={heading}>Media</h3><fieldset disabled={!!disabled||command.busy||command.locked}><Select label="Saved playlist" value={selected} onChange={setPlaylistId} options={playlists.length?playlists.map(id=>({value:id,label:id})):[{value:'',label:'No saved playlists declared'}]}/><p className="hint">Playlists are listed by controller-declared ID. Starting a playlist or a playback action does not change the mode.{!playlists.length&&!disabled?' Unavailable: Start playlist has no declared saved playlist; playback actions remain available.':''}</p><div className="actions"><button type="button" disabled={!selected} onClick={()=>run('Start playlist',{kind:'media.start',playlistId:selected})}>Start playlist</button>{actions.map(action=><button key={action} type="button" className="secondary" onClick={()=>run(actionLabels[action]??action,{kind:'media.control',action})}>{actionLabels[action]??action}</button>)}</div></fieldset>{disabled&&<p className="hint">Unavailable: {disabled}</p>}{extra}{command.locked&&<div className="actions"><button type="button" className="secondary" onClick={command.unlock}>Load current / unlock</button></div>}<p role="status">{command.status}</p></div>;
}
function NanoMappings({integration:s,disabled,api,path,refresh}:{integration:Nano;disabled?:string;api:Api;path:string;refresh:()=>void}){
 const [elementId,setElementId]=useState(''),[taskId,setTaskId]=useState(''),[projectId,setProjectId]=useState('');
 const element=s.elements.some(e=>e.id===elementId)?elementId:s.elements[0]?.id??'',task=s.tasks.some(t=>t.id===taskId)?taskId:s.tasks[0]?.id??'',project=s.projects.some(p=>p.id===projectId)?projectId:s.projects[0]?.id??'';
 const projects=[{value:'',label:'Shared pool'},...s.projects.map(p=>({value:p.id,label:p.id}))];
 const base={source:s,revision:s.revision,api,path:path+'/integration/commands',refresh};
 const command=(state:Nano,cmd:unknown)=>({apiVersion:state.apiVersion,controllerId:state.identity.controllerId,deviceId:state.identity.deviceId,requestId:state.nextRequestId,expectedRevision:state.revision,command:cmd});
 return <div className="mapping-views"><h3>Element assignments</h3><Select label="Element" value={element} onChange={setElementId} options={options(s.elements.map(e=>e.id))}/>{!s.elements.length&&<p>No elements declared.</p>}
 {s.elements.map(e=><div key={e.id} hidden={element!==e.id}><EditForm {...base} title="Element mapping" initial={{project:e.projectId??'',signature:String(e.signature)}} disabled={disabled??(!s.capabilities['elements.assign']?.supported?'Element mapping unsupported':undefined)} build={(state,v)=>command(state,{kind:'elements.assign',elements:[{id:e.id,projectId:v.project||null,signature:Number(v.signature)}]})}>{(v,c)=><><Select label="Element project" value={v.project} onChange={x=>c('project',x)} options={projects}/><Select label="Signature" value={v.signature} onChange={x=>c('signature',x)} options={[{value:'0',label:'Off'},{value:'1',label:'On'}]}/><p className="hint">Current assignment: {e.projectId??'Shared pool'}; signature {e.signature?'on':'off'}.</p></>}</EditForm></div>)}
 <h3>Task assignments</h3><Select label="Task" value={task} onChange={setTaskId} options={options(s.tasks.map(t=>t.id))}/>{!s.tasks.length&&<p>No tasks declared.</p>}
 {s.tasks.map(t=><div key={t.id} hidden={task!==t.id}><EditForm {...base} title="Task mapping" initial={{project:t.overrideProjectId??''}} disabled={disabled??(!s.capabilities['task.assign']?.supported?'Task mapping unsupported':undefined)} build={(state,v)=>command(state,{kind:'task.assign',taskId:t.id,projectId:v.project||null})}>{(v,c)=><><Select label="Task project" value={v.project} onChange={x=>c('project',x)} options={[{value:'',label:'No override'},...projects.slice(1)]}/><p className="hint">Current override: {t.overrideProjectId??'None'}; source project: {t.projectId??'Unknown'}.</p></>}</EditForm></div>)}
 <h3>Project appearance</h3><Select label="Color project" value={project} onChange={setProjectId} options={projects.slice(1)}/>{!s.projects.length&&<p>No projects declared.</p>}
 {s.projects.map(p=><div key={p.id} hidden={project!==p.id}><EditForm {...base} title="Project color" initial={{color:p.color}} disabled={disabled??(!s.capabilities['project.color']?.supported?'Project color unsupported':undefined)} build={(state,v)=>command(state,{kind:'project.color',projectId:p.id,color:v.color})}>{(v,c)=><label>Color<input type="color" value={v.color} onChange={e=>c('color',e.target.value)}/></label>}</EditForm></div>)}
 </div>;
}
function SessionView({session:s,monitor,context,api,refresh,stale,elapsed}:{session:SessionSnapshot;monitor:Monitor;context:Context;api:Api;refresh:()=>void;stale:boolean;elapsed:number}){
 return <article className="session"><div className="section-heading"><h3>{s.label??s.identity.sessionId}</h3><Badge warning={s.freshness!=='current'||stale}>{stale?'Stale connection':s.freshness}</Badge></div><p className="muted">{s.identity.provider} · {s.identity.client} · {s.identity.hostId} / {s.identity.sourceId}</p>
 <Facts items={[
 ['Activity',s.activity],['Attention',s.attention.length?s.attention.map((a,i)=><span key={i} className="attention">{a.kind==='question'?'Question · continuing':`${a.kind} · blocked attention`} </span>):'None observed'],['Observation age',age(s.observationAgeMs+elapsed)],['Read evidence',s.read],['Parent',s.parent.status==='known'?s.parent.identity.sessionId:s.parent.status==='top-level'?'Top-level session':'Unknown'],['Attributable children',`${s.children.active} active / ${s.children.uncertain} uncertain`]
 ]}/><EditForm title="Label" source={monitor} revision={s.label??''} initial={{label:s.label??''}} disabled={!context.control?'Read-only credential':stale?'Snapshot is stale':undefined} api={api} path="/api/monitor/v1/commands" build={(m,v)=>({operation:'label',requestId:m.nextRequestId,identity:s.identity,label:v.label||null})} refresh={refresh}>{(v,c)=><label>Chosen label<input maxLength={160} value={v.label} placeholder="Choose a label" onChange={e=>c('label',e.target.value)}/></label>}</EditForm>
 {s.notices.length>0&&<h4>Retained notices</h4>}{s.notices.map(n=><div className="notice" key={n.id}><p>{n.kind} · {n.id}</p><p className="hint">Acknowledged by: {n.acknowledgedBy.join(', ')||'none'}. This does not establish success or readership.</p><EditForm title="Monitor acknowledgment" source={monitor} revision={n.id+':'+n.acknowledgedBy.join(',')} initial={{consumer:''}} disabled={!context.control?'Read-only credential':stale?'Snapshot is stale':!context.consumers.length?'No configured consumer':undefined} api={api} path="/api/monitor/v1/commands" build={(m,v)=>({operation:'acknowledge',requestId:m.nextRequestId,identity:s.identity,noticeId:n.id,consumerId:v.consumer})} refresh={refresh}>{(v,c)=><Select label="Acknowledge for" value={v.consumer} onChange={x=>c('consumer',x)} options={[{value:'',label:'Choose a consumer'},...context.consumers.filter(x=>!n.acknowledgedBy.includes(x)).map(x=>({value:x,label:x}))]}/>}</EditForm></div>)}
 </article>;
}
function Dashboard({api,disconnect}:{api:Api;disconnect:()=>void}){
 const [context,setContext]=useState<Context>(),[monitor,setMonitor]=useState<Monitor>(),[devices,setDevices]=useState<Record<string,Device>>({}),[view,setView]=useState('activity'),[q,setQ]=useState(''),[provider,setProvider]=useState(''),[error,setError]=useState(''),[feed,setFeed]=useState(false),[now,setNow]=useState(Date.now()),[received,setReceived]=useState(0);
 const refreshRef=useRef<()=>void>(()=>{}),deviceRefresh=useRef<(id:string)=>Promise<void>>(async()=>{});
 useEffect(()=>{
  const stop=new AbortController();let busy=false,again=false;const deviceBusy=new Set<string>(),deviceAgain=new Set<string>(),deviceWaiters=new Map<string,(()=>void)[]>();let current:Context|undefined,latestMonitor:Monitor|undefined;
  const update=(id:string,value:Partial<Device>)=>{if(!stop.signal.aborted)setDevices(old=>({...old,[id]:{...old[id],...value}}));};
  // Resolves after a read that started after this call completed, so a caller can wait for authoritative guards.
  async function refreshDevice(c:Component):Promise<void>{if(stop.signal.aborted)return;
   if(deviceBusy.has(c.id)){deviceAgain.add(c.id);return new Promise<void>(resolve=>{const waiters=deviceWaiters.get(c.id)??[];waiters.push(resolve);deviceWaiters.set(c.id,waiters);});}
   deviceBusy.add(c.id);
   try {const snapshot=await api.request<Snapshot>(`/api/controllers/v1/${c.id}/snapshot`,undefined,stop.signal);let integration:Nano|Pixoo|undefined;
    if(['nanoleaf','pixoo'].includes(c.kind))integration=await api.request<Nano|Pixoo>(`/api/controllers/v1/${c.id}/integration/snapshot`,undefined,stop.signal);
    update(c.id,{snapshot,integration,error:undefined,received:Date.now()});
   }catch(e){update(c.id,{error:e instanceof ApiError?e.code:'unavailable'});}finally{deviceBusy.delete(c.id);if(deviceAgain.delete(c.id)&&!stop.signal.aborted)void refreshDevice(c);else{const waiters=deviceWaiters.get(c.id)??[];deviceWaiters.delete(c.id);waiters.forEach(resolve=>resolve());}}
  }
  async function refresh(){if(busy){again=true;return;}busy=true;
   try {const ctx=await api.request<Context>('/api/dashboard/v1/context',undefined,stop.signal);const next=await api.request<Monitor>('/api/monitor/v1/sessions',undefined,stop.signal);if(stop.signal.aborted)return;current=ctx;setContext(ctx);if(latestMonitor&&latestMonitor.ownerId===next.ownerId&&latestMonitor.snapshot.revision>next.snapshot.revision){setError('stale-snapshot');return;}latestMonitor=next;setMonitor(next);setReceived(Date.now());setError('');}
   catch(e){if(!stop.signal.aborted)setError(e instanceof ApiError?e.code:'unavailable');}finally{busy=false;if(again&&!stop.signal.aborted){again=false;void refresh();}}
  }
  refreshRef.current=()=>void refresh();deviceRefresh.current=id=>{const c=current?.components.find(c=>c.id===id);return c?refreshDevice(c):Promise.resolve();};
  void refresh().then(()=>current?.components.forEach(c=>void refreshDevice(c)));
  void api.feed(stop.signal,()=>void refresh(),value=>{if(!stop.signal.aborted)setFeed(value);});
  const interval=setInterval(()=>{void refresh();current?.components.forEach(c=>void refreshDevice(c));},5000),clock=setInterval(()=>setNow(Date.now()),1000);
  return ()=>{stop.abort();clearInterval(interval);clearInterval(clock);};
 },[api]);
 const sessions=monitor?.snapshot.sessions??[],filtered=sessions.filter(s=>(!provider||s.identity.provider===provider)&&(!q||(s.label??s.identity.sessionId).toLowerCase().includes(q.toLowerCase())));
 return <div className="shell"><a className="skip" href="#main">Skip to content</a><aside><div className="brand"><span className="rabbit">◈</span><div>BUNNY<small>LOCAL INTEGRATION</small></div></div><nav aria-label="Main navigation"><button aria-current={view==='activity'?'page':undefined} onClick={()=>setView('activity')}>Activity <span>{sessions.length}</span></button><p className="nav-label">COMPONENTS</p>{context?.components.map(c=><button key={c.id} aria-current={view===c.id?'page':undefined} onClick={()=>setView(c.id)}>{c.id}<small>{c.kind}</small></button>)}<button aria-current={view==='connections'?'page':undefined} onClick={()=>setView('connections')}>Connections</button></nav><div className="sidebar-foot"><Badge warning={!feed||!!error}>{error?'Connection stale':feed?'Feed connected':'Reconnecting'}</Badge><p>Inspection sends no device commands.</p><button className="secondary" onClick={disconnect}>Disconnect</button></div></aside><main id="main" tabIndex={-1} data-revision={monitor?.snapshot.revision} data-received={received}><header className="top"><span>YOUR WORKSPACE / INTEGRATION</span><span>{context?.control?'Control enabled':'Read only'} · Local</span></header>
 <section hidden={view!=='activity'}><header className="hero"><p className="eyebrow">CODEX & CONNECTED COMPONENTS</p><h1>Your work, at a glance.</h1><p>Activity, attention and device participation. Every action stays explicit.</p></header><div className="stats"><div><strong>{sessions.filter(s=>s.activity==='active').length}</strong><span>Active sessions</span></div><div><strong>{sessions.reduce((n,s)=>n+s.attention.length,0)}</strong><span>Attention signals</span></div><div><strong>{context?.components.length??0}</strong><span>Components</span></div><div><strong>{monitor?.snapshot.collector??'Unknown'}</strong><span>Collector health</span></div></div><div className="filters"><label>Find a session<input type="search" maxLength={120} value={q} onChange={e=>setQ(e.target.value)} placeholder="Chosen label or session ID"/></label><Select label="Provider" value={provider} onChange={setProvider} options={[{value:'',label:'All providers'},...options(['codex','claude'])]}/></div>{error&&<p role="alert" className="warning">{error}. Last observations are stale; edits are disabled.</p>}{!filtered.length&&<div className="empty"><h2>{q||provider?'No matching sessions':'No sessions observed'}</h2><p>{q||provider?'Change the filters to see other observations.':'Component status and supported integration controls remain available.'}</p></div>}<div className="sessions">{sessions.map(s=><div key={key(s)} hidden={!filtered.includes(s)}><SessionView session={s} monitor={monitor!} context={context!} api={api} refresh={()=>refreshRef.current()} stale={!!error||!received||now-received>10000} elapsed={Math.max(0,now-received)} /></div>)}</div></section>
 {context?.components.map(c=><section key={c.id} hidden={view!==c.id}><ComponentView component={c} device={devices[c.id]??{}} context={{...context,control:context.control&&!error}} api={api} refresh={()=>deviceRefresh.current(c.id)} now={now} sessions={sessions}/></section>)}
 <section hidden={view!=='connections'}><header className="hero"><p className="eyebrow">SOURCES & CONNECTIONS</p><h1>Evidence, not assumptions.</h1></header><Facts items={[
 ['Collector',monitor?.snapshot.collector??'Unknown'],['State owner',monitor?.ownerId??'Unknown'],['Feed',feed?'Connected':'Reconnecting'],['Snapshot age',received?age(now-received):'Unknown'],['Lost observations',monitor?.snapshot.lossCount??'Unknown'],['Connection error',error||'None observed']
 ]}/><h2>Observed sources</h2>{[...new Set(sessions.map(s=>`${s.identity.provider} / ${s.identity.hostId} / ${s.identity.sourceId}`))].map(s=><p key={s}>{s}</p>)}{!sessions.length&&<p>No source evidence yet.</p>}<p className="hint">A connected collector does not prove a fresh session, successful task, read chat or physical device result.</p></section><footer>BUNNY / Source observations and deliberate controls</footer></main></div>;
}
function App(){const [api,setApi]=useState<Api>(),[token,setToken]=useState('');return api?<Dashboard api={api} disconnect={()=>{setApi(undefined);setToken('');}}/>:<main className="login"><p className="eyebrow">BUNNY / LOCAL INTEGRATION</p><h1>Your workspace.<br/>One clear view.</h1><p>Connect to inspect agent activity and supported component integration.</p><form onSubmit={e=>{e.preventDefault();if(/^[A-Za-z0-9_-]{43}$/.test(token)){setApi(new Api(token));setToken('');}}}><label>Hub browser access token<input type="password" autoComplete="off" required pattern="[A-Za-z0-9_-]{43}" value={token} onChange={e=>setToken(e.target.value)}/></label><button>Connect</button></form><p className="hint">Use a separately provisioned hub credential, never a native controller token. It stays in this page's memory and is cleared on disconnect or reload.</p></main>;}
createRoot(document.getElementById('root')!).render(<App/>);
