import assert from 'node:assert/strict';
import {chromium} from 'playwright';
import AxeBuilder from '@axe-core/playwright';
import {mkdir,writeFile} from 'node:fs/promises';
import {fixture} from './fixture.mjs';
import {validate} from '@jimmie-potts/device-contracts';
const browser=await chromium.launch({headless:true});
const checks=[];let independentDeviceReadMs;
const visible=(page,role,name)=>page.getByRole(role,{name,exact:true}).filter({visible:true});
// A following edit starts only after the refreshed snapshot is rendered, so it carries fresh guards; a stale draft would surface as the controller's typed conflict.
const settled=async(page,text)=>{await page.waitForFunction(t=>Array.from(document.querySelectorAll('dd')).some(el=>el.textContent.includes(t)),text);await page.evaluate(()=>new Promise(resolve=>requestAnimationFrame(()=>requestAnimationFrame(resolve))));};
async function scenario(name,run,options){const f=await fixture(options),context=await browser.newContext({viewport:{width:1280,height:900},reducedMotion:'reduce'}),page=await context.newPage();page.setDefaultTimeout(12000);const errors=[];page.on('pageerror',e=>errors.push(e.message));try{await page.goto(f.hub.url);await page.getByLabel('Hub browser access token').fill(f.token);await page.getByRole('button',{name:'Connect',exact:true}).click();await page.locator('#main[data-received]:not([data-received="0"])').waitFor();await run(f,page);assert.deepEqual(errors,[]);checks.push(name);}catch(error){console.error(name,await page.locator('section:visible').innerText());throw error;}finally{await context.close();await f.close();}}
async function until(condition){const deadline=Date.now()+10000;while(!condition()){if(Date.now()>deadline)throw new Error('condition-timeout');await new Promise(r=>setTimeout(r,25));}}
async function axe(page){const result=await new AxeBuilder({page}).withTags(['wcag2a','wcag2aa','wcag21aa']).analyze();assert.deepEqual(result.violations.map(v=>({id:v.id,nodes:v.nodes.map(n=>`${n.target.join(' ')}: ${n.failureSummary}`)})),[]);}
try {
 await scenario('empty sessions retain useful controls; keyboard and all view accessibility',async(f,page)=>{
  await page.getByRole('heading',{name:'No sessions observed',exact:true}).waitFor();
  const wall=page.getByRole('button',{name:'wall nanoleaf',exact:true});await wall.focus();await page.keyboard.press('Enter');await page.getByLabel('Device mode').first().waitFor();assert.equal(await visible(page,'button','Switch to Free').isDisabled(),false,'Nanoleaf general controls need no observed session');await axe(page);
  await page.getByLabel('Device mode').first().focus();await page.keyboard.press('ArrowDown');await page.keyboard.press('Tab');assert.ok(await page.getByRole('button',{name:'Apply mode',exact:true}).first().evaluate(el=>el===document.activeElement));await page.keyboard.press('Enter');await page.getByText('queued. Physical result is not confirmed.',{exact:true}).waitFor();
  await page.getByRole('button',{name:'pixel pixoo',exact:true}).click();await page.getByLabel('Monitor provider').waitFor();await page.getByLabel('Brightness (%)').filter({visible:true}).waitFor();assert.equal(await page.getByRole('button',{name:'Pause',exact:true}).filter({visible:true}).isDisabled(),false,'general controls need no observed session');assert.deepEqual(await page.locator('section:visible').getByText('Unavailable:',{exact:false}).allTextContents(),['Unavailable: Scenes are not declared by this controller'],'only the undeclared scene capability is named on Pixoo');await axe(page);await page.setViewportSize({width:390,height:844});await axe(page);assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
  await page.getByRole('button',{name:'Connections',exact:true}).click();await axe(page);
 },{empty:true});
 await scenario('slow device serializes explicit commands while another device remains responsive',async(f,page)=>{
  await page.getByRole('button',{name:'pixel pixoo',exact:true}).click();const mode=page.getByLabel('Device mode').filter({visible:true});await mode.waitFor();f.setDelay(800);const startCount=f.requests.length;
  await until(()=>f.requests.slice(startCount).some(r=>r.id==='pixel'&&r.url==='/controller/v1/snapshot'));
  const start=performance.now();const wall=await fetch(f.hub.url+'/api/controllers/v1/wall/snapshot',{headers:f.headers});assert.equal(wall.status,200);independentDeviceReadMs=performance.now()-start;assert.ok(independentDeviceReadMs<700,'wall does not await pixel');
  await mode.selectOption('monitor');await page.getByRole('button',{name:'Apply mode',exact:true}).filter({visible:true}).click();await page.getByText('configuration accepted. Physical result is not confirmed.',{exact:true}).waitFor();assert.equal(f.writes.at(-1).integration,true);assert.equal(f.writes.at(-1).command.action.mode,'monitor');assert.equal(await page.getByText('Not applied: capacity.',{exact:false}).count(),0);
  f.setDelay(0);await page.waitForFunction(()=>Array.from(document.querySelectorAll('dd')).some(el=>el.textContent==='Monitor'));await page.getByRole('button',{name:'Discard edit / load current'}).filter({visible:true}).click();await mode.selectOption('media');await page.getByRole('button',{name:'Apply mode',exact:true}).filter({visible:true}).click();await page.getByText('configuration accepted. Physical result is not confirmed.',{exact:true}).waitFor();assert.equal(f.writes.at(-1).command.action.mode,'media');
 });
 await scenario('terminal integration failures, known evidence and external control are visible',async(f,page)=>{
  await page.getByRole('button',{name:'wall nanoleaf',exact:true}).click();await page.getByLabel('Layout style').waitFor();f.setQueued(true);await page.getByLabel('Layout style').selectOption('project');await page.getByRole('button',{name:'Apply integration settings',exact:true}).click();await page.getByText('queued. Physical result is not confirmed.',{exact:true}).waitFor();
  const ticket=f.nano.pending[0].requestId;f.nano.pending=[];f.nano.outcomes=[{apiVersion:f.nano.apiVersion,requestId:ticket,outcome:'failed',priorEffects:'none',physicalOutcome:'unknown',failure:{code:'revision-conflict'}}];
  await page.getByText('Result updated: failed · revision-conflict. Prior effects: none.',{exact:false}).waitFor();await page.getByText('failed · revision-conflict',{exact:true}).waitFor();
  f.pixoo.lastOutcome={generation:f.pixoo.generation,renditionGeneration:1,status:'failed',code:'transport-failure'};
  const state=f.states.pixel;state.state.externalControl={status:'known',owner:'external',clock:state.sampleClock};state.state.observation={status:'known',clock:state.sampleClock,evidenceAgeMs:10000,power:{status:'known',value:true},brightness:{status:'known',value:50}};state.state.lastSuccessfulSend={status:'known',requestId:state.nextRequestId,clock:state.sampleClock,operationIds:['mode']};
  await page.getByRole('button',{name:'pixel pixoo',exact:true}).click();await page.getByText('failed · transport-failure',{exact:true}).waitFor();await page.getByText('Sent mode · physical result unknown',{exact:true}).waitFor();const observation=page.locator('dl>div').filter({has:page.getByText('Observation age',{exact:true})}).filter({visible:true});assert.match(await observation.locator('dd').innerText(),/^1[0-9]s$/);await page.getByText('Unavailable: Device is externally controlled',{exact:true}).first().waitFor();assert.equal(await page.getByRole('button',{name:'Apply mode',exact:true}).filter({visible:true}).isDisabled(),true);
 });
 await scenario('rejected older snapshots cannot refresh evidence; expired cursor resync preserves drafts',async(f,page)=>{
  const label=page.getByLabel('Chosen label');await label.fill('Keep my draft');const received=await page.locator('#main').getAttribute('data-received');let stale=true;
  await page.route('**/api/monitor/v1/sessions',async route=>{const response=await route.fetch();const value=await response.json();if(stale)value.snapshot.revision=0;await route.fulfill({response,json:value});});f.reconnect();
  await page.getByRole('alert').filter({hasText:'stale-snapshot'}).waitFor();assert.equal(await page.locator('#main').getAttribute('data-received'),received);assert.equal(await label.inputValue(),'Keep my draft');assert.equal(await page.getByRole('button',{name:'Apply label',exact:true}).isDisabled(),true);
  let expired=false;await page.route('**/api/monitor/v1/changes',async route=>{expired=true;await route.continue({headers:{...route.request().headers(),'last-event-id':'expired:999'}});});stale=false;f.reconnect();await until(()=>expired);await page.waitForFunction(()=>!document.querySelector('[role=alert]'));assert.equal(await label.inputValue(),'Keep my draft');assert.equal(f.writes.length,0);
  const response=await fetch(f.hub.url+'/api/monitor/v1/changes',{headers:{...f.headers,'last-event-id':'expired:999'},signal:AbortSignal.timeout(3000)});const reader=response.body.getReader();assert.match(new TextDecoder().decode((await reader.read()).value),/event: resync/);await reader.cancel();
 });
 await scenario('partial receipt preserves confirmed transmission in browser feedback',async(f,page)=>{
  await page.getByRole('button',{name:'wall nanoleaf',exact:true}).click();await page.getByLabel('Device mode').first().waitFor();
  await page.route('**/api/controllers/v1/wall/commands',async route=>{const request=route.request().postDataJSON();const receipt={apiVersion:'1.0',controllerId:request.controllerId,deviceId:request.deviceId,requestId:request.requestId,configurationRevision:0,generation:request.expectedGeneration,outcome:'partially-applied',priorEffects:'confirmed-transmission',completedOperations:['mode'],uncertainOperations:['refresh'],failure:{code:'transport-failure'}};assert.equal(validate('receipt',receipt),true);f.states.wall.state.lastOutcome={status:'known',receipt};assert.equal(validate('snapshot',f.states.wall),true);await route.fulfill({status:503,json:receipt});});
  await page.getByLabel('Device mode').first().selectOption('Quiet');await page.getByRole('button',{name:'Apply mode',exact:true}).first().click();await page.locator('section:visible [role=status]').filter({hasText:'Result updated: partially-applied'}).waitFor();await page.locator('section:visible [role=status]').filter({hasText:'Prior effects: confirmed-transmission.'}).waitFor();await page.getByText('Completed: mode. Uncertain operations: refresh.',{exact:false}).waitFor();assert.equal(await page.getByText('Not applied:',{exact:false}).count(),0);
 });
 // Hub #151: general controls. The fake Pixoo declares the real controller's capabilities and modes are unsupported on controller v1.
 const guard=f=>({requestId:structuredClone(f.states.pixel.nextRequestId),expectedConfigurationRevision:f.states.pixel.configurationRevision,expectedGeneration:structuredClone(f.states.pixel.generation)});
 const general=f=>f.writes.filter(w=>w.id==='pixel'&&!w.integration).map(w=>w.command);
 await scenario('general controls submit one guarded controller v1 command each in Media without changing the mode',async(f,page)=>{
  await page.getByRole('button',{name:'pixel pixoo',exact:true}).click();const brightness=page.getByLabel('Brightness (%)').filter({visible:true});await brightness.waitFor();assert.equal(await brightness.inputValue(),'60');
  assert.equal(await visible(page,'button','Apply brightness').isDisabled(),true,'an unchanged draft submits nothing');
  let expected=guard(f);await brightness.fill('30');await visible(page,'button','Apply brightness').click();await page.locator('section:visible [role=status]').filter({hasText:/^(queued|Result updated: sent)/}).first().waitFor();
  assert.deepEqual(general(f).at(-1),{apiVersion:'1.0',controllerId:'pixel-controller',deviceId:'pixel',...expected,command:{kind:'brightness.set',percent:30}});
  await page.waitForFunction(()=>Array.from(document.querySelectorAll('dd')).some(el=>el.textContent.includes('Brightness 30%')));
  expected=guard(f);await page.getByRole('combobox',{name:'Screen power',exact:true}).filter({visible:true}).selectOption('off');await visible(page,'button','Apply screen power').click();await until(()=>general(f).length===2);assert.deepEqual(general(f).at(-1).command,{kind:'power.set',on:false});assert.deepEqual(general(f).at(-1).requestId,expected.requestId);assert.equal(general(f).at(-1).expectedConfigurationRevision,expected.expectedConfigurationRevision);
  await page.waitForFunction(()=>Array.from(document.querySelectorAll('dd')).some(el=>el.textContent.includes('Power off')));
  expected=guard(f);await page.getByLabel('Saved playlist').filter({visible:true}).selectOption('playlist-evening');await visible(page,'button','Start playlist').click();await until(()=>general(f).length===3);assert.deepEqual(general(f).at(-1).command,{kind:'media.start',playlistId:'playlist-evening'});assert.equal(general(f).at(-1).expectedConfigurationRevision,expected.expectedConfigurationRevision);assert.equal(f.media.playlistId,'playlist-evening');
  await page.locator('section:visible [role=status]').filter({hasText:/Start playlist: (queued|Result updated: sent)/}).waitFor();
  // Actions stay busy until the refreshed snapshot lands; the next click therefore carries fresh guards. Playwright waits for each button to be enabled.
  for(const [label,action] of [['Pause','pause'],['Next','next'],['Clear','clear']]){const before=general(f).length;await page.getByRole('button',{name:label,exact:true,disabled:false}).filter({visible:true}).waitFor();expected=guard(f);await visible(page,'button',label).click();await until(()=>general(f).length===before+1);assert.deepEqual(general(f).at(-1).command,{kind:'media.control',action});assert.deepEqual(general(f).at(-1).requestId,expected.requestId);assert.equal(general(f).at(-1).expectedConfigurationRevision,expected.expectedConfigurationRevision);}
  assert.deepEqual(f.media.actions,['pause','next','clear'],'every rapid successive action was applied with a fresh ticket');assert.equal(await page.locator('section:visible [role=status]').filter({hasText:'revision-conflict'}).count(),0);assert.equal(f.writes.filter(w=>w.integration).length,0,'no mode command was sent as a side effect');assert.equal(f.pixoo.configuration.mode,'media');assert.equal(f.writes.length,6);
  // Keyboard: unlock the applied brightness form, then the range input and the apply button submit one command.
  await page.locator('form.edit').filter({has:page.getByRole('heading',{name:'Brightness',exact:true})}).getByRole('button',{name:'Discard edit / load current',exact:true}).click();assert.equal(await brightness.inputValue(),'30');
  await brightness.focus();await page.keyboard.press('ArrowDown');await page.keyboard.press('Tab');assert.ok(await visible(page,'button','Apply brightness').evaluate(el=>el===document.activeElement));await page.keyboard.press('Enter');await until(()=>f.writes.length===7);assert.deepEqual(general(f).at(-1).command,{kind:'brightness.set',percent:29});
  await axe(page);
 });
 await scenario('Monitor disables playlist and playback controls with the reason and a one-click explicit switch to Media',async(f,page)=>{
  f.pixoo.configuration.mode='monitor';await page.getByRole('button',{name:'pixel pixoo',exact:true}).click();
  await page.locator('section:visible').getByText('Unavailable: Pixoo is in Monitor',{exact:false}).waitFor();assert.equal(await visible(page,'button','Pause').isDisabled(),true);assert.equal(await page.getByLabel('Saved playlist').filter({visible:true}).isDisabled(),true);
  const brightness=page.getByLabel('Brightness (%)').filter({visible:true});await brightness.fill('55');assert.equal(await visible(page,'button','Apply brightness').isDisabled(),false,'power and brightness stay available in Monitor');await visible(page,'button','Discard edit / load current').first().click();
  const revision=f.pixoo.configurationRevision;await visible(page,'button','Switch to Media').click();await until(()=>f.writes.length===1);assert.equal(f.writes[0].integration,true);assert.deepEqual(f.writes[0].command.action,{operation:'mode',mode:'media'});assert.equal(f.writes[0].command.expectedConfigurationRevision,revision);
  await page.waitForFunction(()=>Array.from(document.querySelectorAll('dd')).some(el=>el.textContent==='Media'));assert.equal(await visible(page,'button','Pause').isDisabled(),false);assert.equal(await visible(page,'button','Switch to Media').count(),0);assert.equal(f.writes.length,1,'the switch sends exactly one mode command and no media command');
  const mode=page.getByLabel('Device mode').filter({visible:true});await mode.selectOption('monitor');await visible(page,'button','Apply mode').click();await until(()=>f.writes.length===2);assert.deepEqual(f.writes[1].command.action,{operation:'mode',mode:'monitor'});
  await page.locator('section:visible').getByText('Unavailable: Pixoo is in Monitor',{exact:false}).waitFor();assert.equal(await visible(page,'button','Pause').isDisabled(),true);
  f.pixoo.pendingMode='media';await page.locator('section:visible').getByText('Pixoo is switching to Media',{exact:false}).waitFor();assert.equal(await visible(page,'button','Switch to Media').count(),0);assert.equal(await visible(page,'button','Pause').isDisabled(),true);
  assert.equal(general(f).length,0,'no general command was sent by mode changes');
 });
 await scenario('general control drafts survive concurrent edits; typed conflicts and uncertain results never retry',async(f,page)=>{
  // Serve the last observed Pixoo snapshot while frozen so the browser's guards are deterministically stale. A poll still in flight when the context closes is abandoned instead of crashing the runner.
  let frozen=null,freeze=false;await page.route('**/api/controllers/v1/pixel/snapshot',async route=>{try{if(freeze&&frozen){await route.fulfill({json:frozen});return;}const response=await route.fetch();frozen=await response.json();await route.fulfill({response,json:frozen});}catch{await route.abort().catch(()=>{});}});
  await page.getByRole('button',{name:'pixel pixoo',exact:true}).click();const brightness=page.getByLabel('Brightness (%)').filter({visible:true});await brightness.waitFor();await until(()=>frozen!==null);freeze=true;await brightness.fill('45');
  const external={apiVersion:'1.0',controllerId:'pixel-controller',deviceId:'pixel',...guard(f),command:{kind:'brightness.set',percent:70}};assert.equal((await fetch(f.hub.url+'/api/controllers/v1/pixel/commands',{method:'POST',headers:f.headers,body:JSON.stringify(external)})).status,200);
  const before=f.writes.length;await visible(page,'button','Pause').click();await page.locator('section:visible [role=status]').filter({hasText:'revision-conflict'}).waitFor();assert.equal(f.writes.length,before+1);
  // The external client consumed the same ticket; the refreshed snapshot carries its sent receipt, which must never be shown as this rejected Pause's outcome.
  assert.equal(JSON.stringify(f.states.pixel.state.lastOutcome.receipt.requestId),JSON.stringify(general(f).at(-1).requestId));
  freeze=false;await page.locator('section:visible').getByText('Changed by another client.',{exact:false}).waitFor();await page.getByRole('button',{name:'Pause',exact:true,disabled:false}).filter({visible:true}).waitFor();assert.equal(await page.locator('section:visible [role=status]').filter({hasText:'Pause: Result updated'}).count(),0,'a rejected ticket does not adopt another client\'s receipt');await page.locator('section:visible [role=status]').filter({hasText:'revision-conflict'}).waitFor();
  assert.equal(await brightness.inputValue(),'45');assert.equal(await visible(page,'button','Apply brightness').isDisabled(),true);
  await brightness.focus();f.reconnect();await page.waitForTimeout(1500);assert.equal(await brightness.inputValue(),'45');assert.ok(await brightness.evaluate(el=>el===document.activeElement),'focus survives reconnect');assert.equal(f.writes.length,before+1,'reconnect replays nothing');
  await visible(page,'button','Discard edit / load current').first().click();assert.equal(await brightness.inputValue(),'70');
  f.setUncertain(true);await visible(page,'button','Resume').click();await page.locator('section:visible [role=status]').filter({hasText:'Uncertain result. Do not repeat this command.'}).waitFor();await page.waitForTimeout(5500);assert.equal(f.writes.length,before+2,'uncertain action is not retried');assert.equal(await visible(page,'button','Resume').isDisabled(),true,'uncertain result stays locked');f.setUncertain(false);
  await visible(page,'button','Load current / unlock').click();await page.getByRole('button',{name:'Resume',exact:true,disabled:false}).filter({visible:true}).waitFor();assert.equal(f.writes.length,before+2);
 });
 await scenario('read-only credentials and undeclared capabilities name their reasons',async(f,page)=>{
  await page.getByRole('button',{name:'Disconnect',exact:true}).click();await page.getByLabel('Hub browser access token').fill(f.reader);await page.getByRole('button',{name:'Connect',exact:true}).click();await page.locator('#main[data-received]:not([data-received="0"])').waitFor();
  f.states.pixel.state.desired.brightness={status:'unknown'};
  await page.getByRole('button',{name:'pixel pixoo',exact:true}).click();await page.getByLabel('Brightness (%)').filter({visible:true}).waitFor();
  await page.locator('section:visible').getByText('Current brightness is unknown; the slider starts at a placeholder, not an observed value.',{exact:false}).waitFor();assert.equal(await page.getByLabel('Brightness (%)').filter({visible:true}).inputValue(),'50');
  assert.ok(await page.locator('section:visible').getByText('Unavailable: Your credential is read-only',{exact:true}).count()>=4,'power, brightness, media and mode name the missing scope');assert.equal(await visible(page,'button','Pause').isDisabled(),true);assert.equal(await visible(page,'button','Apply brightness').isDisabled(),true);await axe(page);
  await page.getByRole('button',{name:'wall nanoleaf',exact:true}).click();await page.locator('section:visible').getByText('Unavailable: Media is not declared by this controller',{exact:true}).waitFor();assert.ok(await page.locator('section:visible').getByText('Unavailable: Your credential is read-only',{exact:true}).count()>=4,'Nanoleaf power, brightness, scenes and mode name the missing scope');assert.equal(await visible(page,'button','Activate scene').isDisabled(),true);assert.equal(await visible(page,'button','Switch to Free').isDisabled(),true,'a read-only credential sees the switch disabled with its reason');await page.locator('section:visible').getByText('No brightness override is active',{exact:false}).waitFor();
  await page.setViewportSize({width:390,height:844});await page.getByRole('button',{name:'pixel pixoo',exact:true}).click();assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'narrow layout has no horizontal overflow');await axe(page);
  assert.equal(f.writes.length,0);
 },{empty:true});
 // Hub #153: Nanoleaf general controls on the declaration of Nanoleaf main 8062849 (#64).
 const wallGuard=f=>({requestId:structuredClone(f.states.wall.nextRequestId),expectedConfigurationRevision:f.states.wall.configurationRevision,expectedGeneration:structuredClone(f.states.wall.generation)});
 const wallGeneral=f=>f.writes.filter(w=>w.id==='wall'&&!w.integration).map(w=>w.command);
 await scenario('Nanoleaf power and brightness work in Work; scenes wait for the explicit Free switch and each control sends one guarded command',async(f,page)=>{
  await page.getByRole('button',{name:'wall nanoleaf',exact:true}).click();const brightness=page.getByLabel('Brightness (%)').filter({visible:true});await brightness.waitFor();
  await page.locator('section:visible').getByText('No brightness override is active',{exact:false}).waitFor();assert.equal(await brightness.inputValue(),'50');
  const scene=page.getByLabel('Saved scene').filter({visible:true});await scene.waitFor();assert.equal(await scene.isDisabled(),true);assert.equal(await visible(page,'button','Activate scene').isDisabled(),true);await page.locator('section:visible').getByText('Unavailable: Nanoleaf is in Work and presents agent status; scene activation needs Free',{exact:true}).waitFor();
  assert.deepEqual(await scene.locator('option').allTextContents(),['Beach Waves',f.sceneB],'user-chosen names label scenes; IDs otherwise');
  const observation=page.locator('dl>div').filter({has:page.getByText('Observation age',{exact:true})}).filter({visible:true});assert.equal(await observation.locator('dd').innerText(),'Unknown','unknown observation stays unknown');
  let expected=wallGuard(f);await brightness.fill('40');await visible(page,'button','Apply brightness').click();await page.locator('section:visible [role=status]').filter({hasText:/^(queued|Result updated: sent)/}).first().waitFor();
  assert.deepEqual(wallGeneral(f).at(-1),{apiVersion:'1.0',controllerId:'wall-controller',deviceId:'wall',...expected,command:{kind:'brightness.set',percent:40}});
  await page.waitForFunction(()=>Array.from(document.querySelectorAll('dd')).some(el=>el.textContent.includes('Brightness 40%')));
  await page.locator('form.edit').filter({has:page.getByRole('heading',{name:'Brightness',exact:true})}).getByRole('button',{name:'Discard edit / load current',exact:true}).click();await page.locator('section:visible').getByText('Brightness override active: 40% until the next explicit mode command',{exact:false}).waitFor();
  expected=wallGuard(f);await page.getByRole('combobox',{name:'Power',exact:true}).filter({visible:true}).selectOption('off');await visible(page,'button','Apply power').click();await until(()=>wallGeneral(f).length===2);assert.deepEqual(wallGeneral(f).at(-1).command,{kind:'power.set',on:false});assert.deepEqual(wallGeneral(f).at(-1).requestId,expected.requestId);assert.equal(wallGeneral(f).at(-1).expectedConfigurationRevision,expected.expectedConfigurationRevision);
  await settled(page,'Power off');assert.equal(f.nano.mode,'Work','power and brightness never change the mode');assert.equal(await scene.isDisabled(),true);
  // Keyboard: the switch is activated with Enter; once Free is observed the switch unmounts, so focus moves to the scene controls instead of the document body.
  expected=wallGuard(f);await visible(page,'button','Switch to Free').focus();await page.keyboard.press('Enter');await until(()=>wallGeneral(f).length===3);assert.deepEqual(wallGeneral(f).at(-1),{apiVersion:'1.0',controllerId:'wall-controller',deviceId:'wall',...expected,command:{kind:'mode.set',mode:'Free'}});assert.equal(f.writes.filter(w=>w.integration).length,0,'the switch uses the controller v1 mode command');
  await page.waitForFunction(()=>Array.from(document.querySelectorAll('dd')).some(el=>el.textContent==='Free'));await page.getByRole('combobox',{name:'Saved scene',exact:true,disabled:false}).filter({visible:true}).waitFor();assert.equal(await visible(page,'button','Switch to Free').count(),0);assert.deepEqual(f.scenes.activated,[],'the switch sends no scene command');
  assert.ok(await scene.evaluate(el=>el===document.activeElement),'keyboard focus moves to the scene controls after the switch unmounts');
  await scene.selectOption(f.sceneB);await scene.focus();const before=f.writes.length;f.reconnect();await page.waitForTimeout(1500);assert.equal(await scene.inputValue(),f.sceneB,'scene selection survives reconnect');assert.ok(await scene.evaluate(el=>el===document.activeElement),'focus survives reconnect');assert.equal(f.writes.length,before,'reconnect replays nothing');
  expected=wallGuard(f);await visible(page,'button','Activate scene').focus();await page.keyboard.press('Enter');await until(()=>wallGeneral(f).length===4);assert.deepEqual(wallGeneral(f).at(-1),{apiVersion:'1.0',controllerId:'wall-controller',deviceId:'wall',...expected,command:{kind:'scene.activate',sceneId:f.sceneB}});assert.deepEqual(f.scenes.activated,[f.sceneB]);
  await page.locator('section:visible [role=status]').filter({hasText:/Activate scene: (queued|Result updated: sent)/}).waitFor();assert.equal(f.nano.mode,'Free','scene activation never changes the mode');
  // Returning to Work is the existing mode control, never a side effect.
  await page.getByRole('button',{name:'Activate scene',exact:true,disabled:false}).filter({visible:true}).waitFor();assert.ok(await visible(page,'button','Activate scene').evaluate(el=>el===document.activeElement),'keyboard focus returns to the activated control once it re-enables');
  // A submitted draft form locks; focus lands on its still-enabled load-current button instead of the document body.
  await brightness.focus();await brightness.fill('35');await page.keyboard.press('Tab');await page.keyboard.press('Enter');await until(()=>wallGeneral(f).length===5);await settled(page,'Brightness 35%');assert.ok(await page.locator('form.edit').filter({has:page.getByRole('heading',{name:'Brightness',exact:true})}).getByRole('button',{name:'Discard edit / load current',exact:true}).evaluate(el=>el===document.activeElement),'a locked form keeps keyboard focus on its enabled load-current button');
  const mode=page.getByLabel('Device mode').filter({visible:true});await mode.selectOption('Work');await visible(page,'button','Apply mode').click();await until(()=>wallGeneral(f).length===6);assert.deepEqual(wallGeneral(f).at(-1).command,{kind:'mode.set',mode:'Work'});
  await page.locator('section:visible').getByText('Unavailable: Nanoleaf is in Work and presents agent status; scene activation needs Free',{exact:true}).waitFor();assert.equal(await visible(page,'button','Activate scene').isDisabled(),true);assert.deepEqual(f.scenes.activated,[f.sceneB]);
  await axe(page);await page.setViewportSize({width:390,height:844});assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await axe(page);
 });
 await scenario('a Nanoleaf scene rejected after Free was observed is a typed failure; pending switches, conflicts and uncertain results never retry',async(f,page)=>{
  f.states.wall.state.desired.mode={status:'known',value:'Free'};f.nano.mode='Free';
  let frozen=null,freeze=false;await page.route('**/api/controllers/v1/wall/snapshot',async route=>{try{if(freeze&&frozen){await route.fulfill({json:frozen});return;}const response=await route.fetch();frozen=await response.json();await route.fulfill({response,json:frozen});}catch{await route.abort().catch(()=>{});}});
  await page.getByRole('button',{name:'wall nanoleaf',exact:true}).click();await page.getByRole('combobox',{name:'Saved scene',exact:true,disabled:false}).filter({visible:true}).waitFor();await until(()=>frozen!==null);freeze=true;
  // The controller left Free after the browser observed it: typed failure before any write, action stays available.
  f.states.wall.state.desired.mode={status:'known',value:'Work'};f.nano.mode='Work';
  await visible(page,'button','Activate scene').click();await page.locator('section:visible [role=status]').filter({hasText:'unsupported-capability'}).waitFor();assert.deepEqual(f.scenes.activated,[]);assert.equal(f.writes.length,1);
  freeze=false;await page.locator('section:visible').getByText('Unavailable: Nanoleaf is in Work and presents agent status; scene activation needs Free',{exact:true}).waitFor();assert.equal(await visible(page,'button','Activate scene').isDisabled(),true,'the refreshed snapshot shows the observed mode');
  // A pending mode change disables scenes with the reason and hides the switch.
  f.states.wall.state.pending=[{requestId:structuredClone(f.states.wall.nextRequestId),command:{kind:'mode.set',mode:'Free'},generation:structuredClone(f.states.wall.generation)}];await page.locator('section:visible').getByText('Unavailable: Nanoleaf is switching to Free; wait for the observed mode',{exact:true}).waitFor();assert.equal(await visible(page,'button','Switch to Free').count(),0);
  f.states.wall.state.pending=[];f.states.wall.state.desired.mode={status:'known',value:'Free'};f.nano.mode='Free';await page.getByRole('button',{name:'Activate scene',exact:true,disabled:false}).filter({visible:true}).waitFor();await until(()=>frozen.state.desired.mode.value==='Free');freeze=true;
  // Another client consumes the ticket: typed conflict, nothing repeated, action available after the refreshed snapshot.
  const external={apiVersion:'1.0',controllerId:'wall-controller',deviceId:'wall',...wallGuard(f),command:{kind:'brightness.set',percent:70}};assert.equal((await fetch(f.hub.url+'/api/controllers/v1/wall/commands',{method:'POST',headers:f.headers,body:JSON.stringify(external)})).status,200);
  await visible(page,'button','Activate scene').click();await page.locator('section:visible [role=status]').filter({hasText:'revision-conflict'}).waitFor();assert.deepEqual(f.scenes.activated,[]);
  freeze=false;await page.getByRole('button',{name:'Activate scene',exact:true,disabled:false}).filter({visible:true}).waitFor();assert.equal(await page.locator('section:visible [role=status]').filter({hasText:'Activate scene: Result updated'}).count(),0,'a rejected ticket does not adopt another client\'s receipt');
  const submitted=f.writes.length;f.setUncertain(true);await visible(page,'button','Activate scene').click();await page.locator('section:visible [role=status]').filter({hasText:'Uncertain result. Do not repeat this command.'}).waitFor();await page.waitForTimeout(5500);assert.equal(f.writes.length,submitted+1,'uncertain scene command is not retried');assert.equal(await visible(page,'button','Activate scene').isDisabled(),true,'uncertain result stays locked');f.setUncertain(false);
  await visible(page,'button','Load current / unlock').click();await page.getByRole('button',{name:'Activate scene',exact:true,disabled:false}).filter({visible:true}).waitFor();assert.equal(f.writes.length,submitted+1);assert.equal(f.writes.filter(w=>w.integration).length,0);
 });
 const receipt={synthetic:true,physical:false,passed:true,checks,pixelReadDelayMs:800,independentDeviceReadMs};const output=process.env.DASHBOARD_RECEIPTS??'/tmp/gh6-dashboard-receipts';await mkdir(output,{recursive:true});await writeFile(output+'/matrix.json',JSON.stringify(receipt,null,2));console.log(JSON.stringify(receipt));
}finally{await browser.close();}
