/* Prism finish kit: dependency-free SVG components and layout-driven UI motion.
   Ported from codex-nanoleaf bridge/prism.js (see README.md for the revision and hashes).
   No network, device access, storage, polling, or task-state writes. */
const NS = 'http://www.w3.org/2000/svg', R = 25, INNER = 18.7, D = R * Math.cos(Math.PI / 6), ASSEMBLY_SECONDS = 2, FLOW_SECONDS = 2;
let instance = 0;
const clamp = (t: number) => Math.max(0, Math.min(1, t)), ease = (t: number) => { t = clamp(t); return t * t * (3 - 2 * t); }, phase = (p: number, s: number, d: number) => clamp((p - s) / d);
const rad = (a: number) => a * Math.PI / 180, deg = (a: number) => a * 180 / Math.PI, point = (r: number, a: number): [number, number] => [r * Math.cos(rad(a)), r * Math.sin(rad(a))];
const fmt = (n: number) => Number(n.toFixed(5)), xy = (p: [number, number]) => p.map(fmt).join(' '), hex = (r: number, a = 30) => Array.from({ length: 6 }, (_, i) => xy(point(r, a + i * 60))).join(' ');
const esc = (s: unknown) => String(s).replace(/[&<>"']/g, c => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[c] as string));
/** A six-digit hex color, or null. Every Line color and every status token must pass this. */
export const color = (s: unknown): string | null => typeof s === 'string' && /^#[0-9a-f]{6}$/i.test(s) ? s : null;
const pale = (s: string) => '#' + (s.slice(1).match(/../g) as string[]).map(c => Math.round(parseInt(c, 16) * .16 + 255 * .84).toString(16).padStart(2, '0')).join('');
const attr = (el: Element | null | undefined, key: string, val: unknown) => { if (!el) return; const text = String(val); if (el.getAttribute(key) !== text) el.setAttribute(key, text); };
const median = (values: number[]) => { const a = [...values].sort((a, b) => a - b); return a[Math.floor(a.length / 2)]; };
const mod = (a: number, b: number) => ((a % b) + b) % b;
const delta60 = (a: number) => mod(a + 30, 60) - 30;
function defs(p: string) { return `
 <linearGradient id="${p}body" x1="0" y1="0" x2="0" y2="1"><stop stop-color="#d5f3ff" stop-opacity=".33"/><stop offset=".13" stop-color="#173449" stop-opacity=".93"/><stop offset=".34" stop-color="#101f30" stop-opacity=".97"/><stop offset=".54" stop-color="#1c3548" stop-opacity=".75"/><stop offset=".78" stop-color="#08111e" stop-opacity=".98"/><stop offset="1" stop-color="#cbd8fc" stop-opacity=".24"/></linearGradient>
 <linearGradient id="${p}rim" x1="0" y1="0" x2="1" y2="1"><stop stop-color="#f0fdff" stop-opacity=".85"/><stop offset=".15" stop-color="#a2ddea" stop-opacity=".32"/><stop offset=".4" stop-color="#263e51" stop-opacity=".5"/><stop offset=".67" stop-color="#799dba" stop-opacity=".24"/><stop offset=".86" stop-color="#dbc4ff" stop-opacity=".56"/><stop offset="1" stop-color="#7587ae" stop-opacity=".36"/></linearGradient>
 <linearGradient id="${p}pane" x1="0" y1="0" x2="1" y2="1"><stop stop-color="#a4e2f5" stop-opacity=".23"/><stop offset=".18" stop-color="#263749" stop-opacity=".74"/><stop offset=".52" stop-color="#0b1521" stop-opacity=".94"/><stop offset="1" stop-color="#8874c2" stop-opacity=".23"/></linearGradient>
 <linearGradient id="${p}edge"><stop stop-color="#d4fcff" stop-opacity=".8"/><stop offset=".24" stop-color="#79d9ed" stop-opacity=".35"/><stop offset=".57" stop-color="#cae7ff" stop-opacity=".08"/><stop offset=".82" stop-color="#d5bdff" stop-opacity=".4"/><stop offset="1" stop-color="#f3e7ff" stop-opacity=".75"/></linearGradient>
 <linearGradient id="${p}reflection" x1="0" y1="0" x2="1" y2="1"><stop stop-color="white" stop-opacity="0"/><stop offset=".34" stop-color="white" stop-opacity="0"/><stop offset=".39" stop-color="white" stop-opacity=".12"/><stop offset=".43" stop-color="white" stop-opacity=".025"/><stop offset=".64" stop-color="white" stop-opacity=".015"/><stop offset=".67" stop-color="white" stop-opacity=".10"/><stop offset=".69" stop-color="white" stop-opacity="0"/></linearGradient>
 <linearGradient id="${p}caustic"><stop stop-color="white" stop-opacity="0"/><stop offset=".2" stop-color="white" stop-opacity=".03"/><stop offset=".38" stop-color="white" stop-opacity=".25"/><stop offset=".42" stop-color="white" stop-opacity=".46"/><stop offset=".47" stop-color="white" stop-opacity=".025"/><stop offset="1" stop-color="white" stop-opacity="0"/></linearGradient>
 <filter id="${p}wide" x="-55%" y="-800%" width="210%" height="1700%" color-interpolation-filters="sRGB"><feGaussianBlur stdDeviation="20"/><feComponentTransfer><feFuncA type="linear" slope="3.4"/></feComponentTransfer></filter>
 <filter id="${p}soft" x="-35%" y="-450%" width="170%" height="1000%" color-interpolation-filters="sRGB"><feGaussianBlur stdDeviation="6"/><feComponentTransfer><feFuncA type="linear" slope="2.4"/></feComponentTransfer></filter>
 <filter id="${p}near" x="-30%" y="-200%" width="160%" height="500%" color-interpolation-filters="sRGB"><feGaussianBlur stdDeviation="2.1"/></filter>
 <filter id="${p}hubglow" x="-160%" y="-160%" width="420%" height="420%" color-interpolation-filters="sRGB"><feGaussianBlur stdDeviation="9"/></filter>
 <filter id="${p}number" x="-100%" y="-100%" width="300%" height="300%"><feGaussianBlur stdDeviation="1.8"/></filter>
 <clipPath id="${p}zone0"><rect x="-126" y="-11" width="126" height="22" rx="1"/></clipPath>
 <clipPath id="${p}zone1"><rect x="0" y="-11" width="126" height="22" rx="1"/></clipPath>
 <clipPath id="${p}paneclip"><polygon points="${hex(INNER)}"/></clipPath>`; }
function beamDefs(p: string, index: number) { return [0, 1].map(z => `<linearGradient id="${p}beam${index}-${z}"><stop data-paint="${index}-${z}" stop-color="${z ? '#b489ff' : '#65e7ff'}" stop-opacity="0"/><stop offset=".18" data-paint="${index}-${z}" stop-color="#65e7ff" stop-opacity=".06"/><stop offset=".46" data-paint="${index}-${z}" stop-color="#65e7ff" stop-opacity=".55"/><stop offset=".75" data-paint="${index}-${z}" stop-color="#65e7ff"/><stop offset=".94" data-paint="${index}-${z}" data-hot="true" stop-color="#f3ffff"/><stop offset="1" data-paint="${index}-${z}" stop-color="#65e7ff" stop-opacity=".25"/></linearGradient>`).join(''); }
function packet(p: string, i: number, z: number) { return `<g data-packet="${i}" data-zone="${z}" transform="translate(${z ? 126 : -126} 0) scale(${z ? -1 : 1} 1)"><path d="M-176 0Q-118 -1.8 -70 -4L-13 -5.3Q1 -5.3 2 0Q1 5.3 -13 5.3L-70 4Q-118 1.8 -176 0Z" fill="url(#${p}beam${i}-${z})"/><path d="M-144 0L-11 -1.9Q3 -1.9 3 0Q3 1.9 -11 1.9Z" fill="url(#${p}beam${i}-${z})"/><ellipse cx="-2.2" rx="3.5" ry="2.7" fill="#f4ffff" opacity=".92"/></g>`; }
function lightLayer(p: string, i: number, z: number, filter: string, opacity: number, part: string) { return `<g data-part="${part}" ${filter ? `filter="url(#${p + filter})"` : ''} opacity="${opacity}"><g clip-path="url(#${p}zone${z})"><rect data-solid="${i}-${z}" data-bed="${i}" x="-126" y="-5.5" width="252" height="11" rx="5.5" fill="${z ? '#b489ff' : '#65e7ff'}" opacity=".44"/>${part === 'zone-core' ? `<rect data-solid="${i}-${z}" data-hot-solid="true" data-bed="${i}" x="-126" y="-2.1" width="252" height="4.2" rx="2.1" fill="#eaffff" opacity=".6"/>` : ''}${packet(p, i, z)}</g></g>`; }
function shell(p: string) { return `<g data-part="tube-body"><path d="M-128 -9L-123 -16H123L128 -9V9L123 16H-123L-128 9Z" fill="url(#${p}body)" stroke="url(#${p}edge)" stroke-width=".65"/><path d="M-123 -15L-117 -10H117L123 -15Z" fill="#c6eaf7" opacity=".14"/><path d="M-123 15L-117 10H117L123 15Z" fill="#8b97c1" opacity=".16"/><path d="M-128 -9L-121 -8V8L-128 9ZM128 -9L121 -8V8L128 9Z" fill="url(#${p}rim)"/><path d="M-125 -8H125M-125 8H125" fill="none" stroke="#07111c" stroke-width="2" opacity=".55"/></g>`; }
function front(p: string) { return `<g data-part="tube-facets" pointer-events="none"><path d="M-123 -16H123L128 -9M-128 9L-123 16H123" stroke="url(#${p}edge)" stroke-width=".8" fill="none"/><path d="M-119 -13H119M-119 13H119" stroke="#e6f6ff" stroke-opacity=".19" stroke-width=".45"/><path d="M-117 -10H117M-117 10H117" stroke="url(#${p}edge)" stroke-width=".72"/><path d="M-117 -9H117V9H-117Z" fill="url(#${p}reflection)"/><path d="M-116 -12Q-56 -10 9 -12T115 -12M-116 12Q-17 9 115 12" stroke="url(#${p}caustic)" stroke-width="1.3" fill="none"/><path d="M-112 -14L-104 -11M-99 -14L-93 -11M83 11L90 14M97 11L104 14" stroke="#dcf8ff" stroke-width=".35" opacity=".30"/><path d="M-123 -11V11M123 -11V11" stroke="#c5ecfa" stroke-opacity=".26" stroke-width=".6"/><path d="M-105 -14H-82M61 14H91" stroke="white" stroke-opacity=".6" stroke-width=".55"/></g>`; }
function tube(p: string, i: number) { return `<g data-part="diffuse-spill" data-spill="${i}">${[0, 1].map(z => lightLayer(p, i, z, 'wide', .66, 'wide-spill') + lightLayer(p, i, z, 'soft', .45, 'near-spill')).join('')}</g>${shell(p)}<g data-part="light-core">${[0, 1].map(z => lightLayer(p, i, z, 'near', .8, 'refracted-core') + lightLayer(p, i, z, '', 1, 'zone-core')).join('')}</g>${front(p)}<g data-spark="${i}" data-part="center-spark" opacity="0"><g filter="url(#${p}soft)"><ellipse rx="8" ry="6" data-solid="${i}-0" fill="#65e7ff"/><ellipse rx="5" ry="8" data-solid="${i}-1" fill="#b489ff"/></g><path d="M0 -10L1.3 -2L6 0L1.3 2L0 10L-1.3 2L-6 0L-1.3 -2Z" fill="#f1ffff"/><circle r="1.9" fill="white"/></g>`; }
function rimPiece(p: string, j: number) {
 const a = 150 + j * 60, b = a + 60, outerA = point(R, a), outerB = point(R, b), innerA = point(INNER, a), innerB = point(INNER, b);
 const facet = [outerA, outerB, innerB, innerA].map(xy).join(' ');
 return `<g data-rim="${j}" data-part="rim-${j}" data-pivot-a="${outerA}" data-pivot-b="${outerB}"><polygon points="${facet}" fill="url(#${p}rim)"/><polygon data-hub-tint="${j}" points="${facet}" fill="#75ddff" opacity=".09"/><path d="M${xy(outerA)}L${xy(outerB)}" stroke="url(#${p}edge)" stroke-width=".72" fill="none"/><path data-hub-edge="${j}" d="M${xy(innerA)}L${xy(innerB)}" stroke="#c5e7f9" stroke-opacity=".8" stroke-width=".72" fill="none"/><path d="M${xy(point(22, a))}L${xy(point(22, b))}" stroke="#b3d8ed" stroke-opacity=".10" stroke-width=".65" fill="none"/></g>`;
}
function connector(p: string) { return `<g data-part="connector-ambient"><polygon data-hub-aura="true" points="${hex(21)}" fill="none" stroke="#77dfff" stroke-width="3" opacity=".2" filter="url(#${p}hubglow)"/></g><g data-part="connector-pane"><polygon points="${hex(INNER + .15)}" fill="url(#${p}pane)"/><g clip-path="url(#${p}paneclip)"><path d="M-28 -19L25 -8L-6 2L-28 -5Z" fill="#d6f5ff" opacity=".075"/><path d="M-24 12L26 -3L28 6L-17 20Z" fill="#a699d8" opacity=".045"/><path d="M-13 -10L5 -16M-14 -8L-3 -12" stroke="#efffff" stroke-width=".38" opacity=".38"/><path d="M-19 4L17 -8M-18 6L15 -6" stroke="#cadfff" stroke-width=".4" opacity=".08"/></g></g><g data-part="connector-rim">${Array.from({ length: 6 }, (_, j) => rimPiece(p, j)).join('')}</g>`; }
function numeral(p: string, value: unknown) { return `<g data-part="luminous-numeral" font-family="'Cascadia Mono',Consolas,monospace" font-size="11" font-weight="500" text-anchor="middle" dominant-baseline="middle"><text fill="#d9efff" filter="url(#${p}number)" opacity=".75">${esc(String(value).padStart(2, '0'))}</text><text fill="#e7f5ff" stroke="#081423" stroke-width=".5" paint-order="stroke">${esc(String(value).padStart(2, '0'))}</text></g>`; }

export type LayoutInput = { version: 1; name?: string; source?: string; rootIds?: (string | number)[]; nodes: { id: string | number; x: number; y: number; sourceIds?: (string | number)[] }[]; lines: { id: string | number; number?: string | number; a: string | number; b: string | number; zoneIds?: (string | number)[]; colors?: string[] }[] };
export type Node = { id: string; x: number; y: number; index: number; adj: { edge: number; to: number }[]; sourceIds: (string | number)[]; angle: number; parent: number | null; incoming: number; root: number; depth: number; cx: number; cy: number; growth: number; unfold: number };
export type Line = { id: string; number: string | number; a: number; b: number; length: number; index: number; zoneIds: (string | number)[]; colors: [string, string]; angle: number; da: number; db: number; tubeLength: number; finalCx: number; finalCy: number; tree: boolean; parent: number; child: number; reverse: boolean; deployAngle: number; start: number; duration: number; extension: number; cx: number; cy: number; currentAngle: number; fold: number };
export type Layout = { version: 1; name: string; nodes: Node[]; lines: Line[]; roots: number[]; rootIds: string[]; order: number[]; maxDepth: number; scale: number; duration: number; source: string };
export type Mode = 'work' | 'quiet' | 'free';
export type LineMetadata = { ariaLabel?: string; status?: string | null };
export type RendererSnapshot = { progress: number; playing: boolean; lightPhase: number; selected: string[]; highlighted: string[]; activity: string[]; pending: string[]; mode: Mode; pauseReasons: string[]; lines: number; connectors: number; components: number; rootIds: string[]; loops: number; reducedMotion: boolean };
export type RendererOptions = { animate?: boolean; onSelect?: (event: Event, line: Line) => void; onFrame?: (snapshot: RendererSnapshot) => void };
type Parts = Record<string, Record<string, SVGElement>>;
type ReducedMotion = { matches: boolean; addEventListener(type: 'change', listener: () => void): void; removeEventListener(type: 'change', listener: () => void): void };

/** Rejects an invalid layout before any listener or observer exists, then returns the drawn layout with its tree, roots and timing. */
export function validate(input: LayoutInput | null | undefined): Layout {
 if (!input || input.version !== 1 || !Array.isArray(input.nodes) || !Array.isArray(input.lines)) throw Error('A version 1 layout needs connectors and Lines.');
 if (Object.hasOwn(input, 'rootId')) throw Error('Use rootIds with one app-selected root per component.');
 if (input.nodes.length < 2 || input.nodes.length > 300 || input.lines.length < 1 || input.lines.length > 300) throw Error('Choose a layout with 1–300 Lines and 2–300 connectors.');
 const seen = new Set<string>(), nodes: Node[] = input.nodes.map((n, i) => { if (n.id === undefined || !['string', 'number'].includes(typeof n.id) || String(n.id).length > 120) throw Error('Every connector needs a short ID.'); const id = String(n.id); if (seen.has(id)) throw Error('Connector IDs must be unique.'); seen.add(id); if (!Number.isFinite(n.x) || !Number.isFinite(n.y) || Math.abs(n.x) > 1e7 || Math.abs(n.y) > 1e7) throw Error('Connector positions must be finite coordinates.'); return { id, x: n.x, y: n.y, index: i, adj: [], sourceIds: n.sourceIds || [n.id], angle: 0, parent: null, incoming: -1, root: i, depth: 0, cx: n.x, cy: n.y, growth: 1, unfold: 1 }; });
 const nodeMap = new Map(nodes.map(n => [n.id, n])), edgeIds = new Set<string>(), pairs = new Set<string>();
 const lines: Line[] = input.lines.map((l, i) => {
  const id = String(l.id ?? ''); if (!id || id.length > 150 || edgeIds.has(id)) throw Error('Every Line needs a unique, stable ID.'); edgeIds.add(id);
  const a = nodeMap.get(String(l.a)), b = nodeMap.get(String(l.b)); if (!a || !b || a === b) throw Error('Each Line must join two different connectors.');
  const pair = [a.index, b.index].sort((a, b) => a - b).join(':'); if (pairs.has(pair)) throw Error('Two Lines cannot occupy the same connection.'); pairs.add(pair);
  const length = Math.hypot(b.x - a.x, b.y - a.y); if (length < 1e-3) throw Error('Connector centers must be distinct.');
  if (l.colors !== undefined && (!Array.isArray(l.colors) || l.colors.length !== 2 || l.colors.some(c => !color(c)))) throw Error('Each Line color needs two six-digit hex colors.');
  const line: Line = { id, number: l.number ?? i + 1, a: a.index, b: b.index, length, index: i, zoneIds: l.zoneIds ? [...l.zoneIds] : [id + ':0', id + ':1'], colors: l.colors ? [l.colors[0], l.colors[1]] : ['#35e7ff', '#a96aff'], angle: 0, da: 0, db: 0, tubeLength: 0, finalCx: 0, finalCy: 0, tree: false, parent: -1, child: -1, reverse: false, deployAngle: 0, start: 0, duration: 0, extension: 0, cx: 0, cy: 0, currentAngle: 0, fold: 0 };
  if (!['string', 'number'].includes(typeof line.number) || String(line.number).length > 12) throw Error('Line labels must be short numbers or text.');
  if (line.zoneIds.length !== 2 || line.zoneIds.some(z => !['string', 'number'].includes(typeof z))) throw Error('A Line needs two zone IDs.');
  a.adj.push({ edge: i, to: b.index }); b.adj.push({ edge: i, to: a.index }); return line;
 });
 if (nodes.some(n => !n.adj.length)) throw Error('Remove connectors that have no Lines.');
 const scale = 200 / median(lines.map(l => l.length)); nodes.forEach(n => { n.x *= scale; n.y *= scale; });
 nodes.forEach(n => { const other = nodes[n.adj[0].to]; n.angle = mod(deg(Math.atan2(other.y - n.y, other.x - n.x)), 60); if (n.adj.length > 6) throw Error('A hexagonal connector supports at most six Lines.'); const faces = new Set<number>(); for (const a of n.adj) { const q = nodes[a.to], angle = deg(Math.atan2(q.y - n.y, q.x - n.x)); if (Math.abs(delta60(angle - n.angle)) > 1) throw Error('This layout has joins outside the six flat faces of a Lines connector.'); const face = mod(Math.round((angle - n.angle) / 60), 6); if (faces.has(face)) throw Error('Two Lines share one connector face.'); faces.add(face); } });
 lines.forEach(l => { const a = nodes[l.a], b = nodes[l.b]; l.angle = deg(Math.atan2(b.y - a.y, b.x - a.x)); l.length *= scale; l.da = D / Math.cos(rad(delta60(l.angle - a.angle))); l.db = D / Math.cos(rad(delta60(l.angle + 180 - b.angle))); l.tubeLength = l.length - l.da - l.db; l.finalCx = (a.x + b.x) / 2; l.finalCy = (a.y + b.y) / 2; if (l.tubeLength < 40) throw Error('This layout contains a Line too short for its connectors.'); });
 const components: number[][] = [], discovered = new Set<number>();
 for (let seed = 0; seed < nodes.length; seed++) { if (discovered.has(seed)) continue; const component = [seed]; discovered.add(seed); for (const cur of component) for (const a of nodes[cur].adj) if (!discovered.has(a.to)) { discovered.add(a.to); component.push(a.to); } components.push(component); }
 const requested = input.rootIds;
 if (requested !== undefined && (!Array.isArray(requested) || requested.some(id => !['string', 'number'].includes(typeof id)))) throw Error('rootIds must be an array of connector IDs.');
 const requestedIndexes = requested?.map(id => nodeMap.get(String(id))?.index);
 if (requestedIndexes?.some(index => index === undefined) || new Set(requestedIndexes || []).size !== (requestedIndexes || []).length) throw Error('rootIds must contain distinct connector IDs from this layout.');
 function preferredRoot(component: number[]) {
  const junctions = component.filter(index => nodes[index].adj.length >= 2), candidates = junctions.length ? junctions : component;
  const xs = component.map(index => nodes[index].x), ys = component.map(index => nodes[index].y), cx = (Math.min(...xs) + Math.max(...xs)) / 2, cy = (Math.min(...ys) + Math.max(...ys)) / 2;
  const spread = (index: number) => junctions.reduce((sum, other) => sum + Math.hypot(nodes[index].x - nodes[other].x, nodes[index].y - nodes[other].y), 0), center = (index: number) => Math.hypot(nodes[index].x - cx, nodes[index].y - cy), compare = (a: number, b: number) => Math.abs(a - b) < 1e-6 ? 0 : a - b;
  return [...candidates].sort((a, b) => nodes[b].adj.length - nodes[a].adj.length || compare(spread(a), spread(b)) || compare(center(a), center(b)) || nodes[a].id.localeCompare(nodes[b].id))[0];
 }
 const roots = components.map(component => { if (!requestedIndexes) return preferredRoot(component); const matches = requestedIndexes.filter(index => component.includes(index as number)) as number[]; if (matches.length !== 1) throw Error('rootIds must provide exactly one root for each disconnected component.'); return matches[0]; });
 if (requestedIndexes && requestedIndexes.length !== components.length) throw Error('rootIds must provide exactly one root for each disconnected component.');
 const visited = new Set<number>(), order: number[] = []; let maxDepth = 0;
 for (const root of roots) { nodes[root].parent = null; nodes[root].depth = 0; nodes[root].root = root; const queue = [root]; visited.add(root); for (const cur of queue) { order.push(cur); const node = nodes[cur]; for (const a of node.adj) if (!visited.has(a.to)) { visited.add(a.to); queue.push(a.to); const child = nodes[a.to], edge = lines[a.edge]; child.parent = cur; child.incoming = a.edge; child.root = root; child.depth = node.depth + 1; edge.tree = true; edge.parent = cur; edge.child = a.to; maxDepth = Math.max(maxDepth, child.depth); } } }
 const wave = .62 / Math.max(1, maxDepth);
 lines.forEach(l => { if (l.parent < 0) l.parent = nodes[l.a].depth <= nodes[l.b].depth ? l.a : l.b; if (l.child < 0) l.child = l.parent === l.a ? l.b : l.a; l.reverse = l.parent !== l.a; const a = nodes[l.parent], b = nodes[l.child]; l.deployAngle = deg(Math.atan2(b.y - a.y, b.x - a.x)); l.start = l.tree ? .12 + (b.depth - 1) * wave : .79; l.duration = l.tree ? wave : .20; });
 return { version: 1, name: String(input.name || 'Custom layout'), nodes, lines, roots, rootIds: roots.map(index => nodes[index].id), order, maxDepth, scale, duration: ASSEMBLY_SECONDS, source: input.source || '' };
}
function lineSet(layout: Layout, ids: Iterable<string | number> | string | null | undefined, label: string) { if (ids == null) return new Set<string>(); let values: (string | number)[]; try { values = typeof ids === 'string' ? [ids] : [...ids]; } catch { throw Error(label + ' must be an iterable of Line IDs.'); } const known = new Set(layout.lines.map(line => line.id)), result = new Set(values.map(String)); if ([...result].some(id => !known.has(id))) throw Error(label + ' contains an unknown Line ID.'); return result; }

/** Draws one connector layout as crystal tubes and hexagonal connectors, with an opening assembly, a shared two-second Work flow and selection, highlight, pending and focus rings. It touches only its host element. */
export class Renderer {
 host: HTMLElement; p: string; options: RendererOptions; progress = 0; playing = false; speed = 1; glow = 1.55; mode: Mode = 'work'; direction: 1 | -1 = 1;
 flowElapsed = 0; flowLast: number | null = null; assemblyLast: number | null = null; lightPhase = 0; frameId = 0; selection = new Set<string>(); highlighted = new Set<string>(); activity = new Set<string>(); pending = new Set<string>(); hovered = new Set<string>(); focused = new Set<string>(); lineMetadata = new Map<string, { ariaLabel?: string; status: string | null }>(); labelTransforms = new Map<string, string>(); showNumbers = false; flowEpochEstablished = false; pauseReasons = new Set<string>(); destroyed = false; assemblyReason: string | null = null; turn = 0;
 layout!: Layout; svg!: SVGSVGElement; parts!: Parts; bounds!: [number, number, number, number]; packets!: SVGElement[]; beds!: SVGElement[]; spills!: SVGElement[]; sparks!: SVGElement[]; materialLayers!: SVGElement[]; rims!: SVGElement[][];
 reduced: ReducedMotion; visibilityObserver: IntersectionObserver | null; removalObserver: MutationObserver | null; inputAbort?: AbortController;
 private _hidden: () => void; private _reduce: () => void;
 constructor(host: HTMLElement, layout: LayoutInput, options: RendererOptions = {}) {
  if (!host) throw Error('A host element is required.');
  validate(layout); // Reject invalid input before acquiring listeners or observers.
  this.host = host; this.p = 'pr' + (++instance) + '-'; this.options = options;
  this.reduced = typeof matchMedia === 'function' ? matchMedia('(prefers-reduced-motion: reduce)') : { matches: false, addEventListener() { }, removeEventListener() { } };
  const rect = host.getBoundingClientRect(); this._setPauseReason('host-hidden', !(rect.bottom >= 0 && rect.top < innerHeight));
  this.visibilityObserver = typeof IntersectionObserver === 'function' ? new IntersectionObserver(entries => { const latest = entries.at(-1); if (latest) this._setPauseReason('host-hidden', !latest.isIntersecting); }) : null; this.visibilityObserver?.observe(host);
  this._hidden = () => this._setPauseReason('document-hidden', document.hidden);
  this._reduce = () => { if (this.reduced.matches && this.playing) this._completeAssembly(this.assemblyReason || 'first'); else { this.assemblyLast = null; this.flowLast = null; this.render(performance.now()); } this.schedule(); };
  document.addEventListener('visibilitychange', this._hidden); this.reduced.addEventListener('change', this._reduce); this._hidden();
  this.setLayout(layout, { animate: options.animate !== false });
  this.removalObserver = typeof MutationObserver === 'function' ? new MutationObserver(() => { if (!host.isConnected) this.destroy(); }) : null;
  this.removalObserver?.observe(document.documentElement, { childList: true, subtree: true });
 }
 _setPauseReason(reason: string, paused: boolean) { paused ? this.pauseReasons.add(reason) : this.pauseReasons.delete(reason); this.assemblyLast = null; this.flowLast = null; if (this.pauseReasons.size) { cancelAnimationFrame(this.frameId); this.frameId = 0; } else this.schedule(); }
 _establishFlowPhase() { this.flowElapsed = 0; this.flowLast = null; this.lightPhase = 0; this.flowEpochEstablished = true; }
 _completeAssembly(reason: string) { const wasIncomplete = this.playing || this.progress < 1; this.progress = 1; this.playing = false; this.assemblyLast = null; if (!this.flowEpochEstablished || wasIncomplete && ['first', 'replay', 'interaction'].includes(reason)) this._establishFlowPhase(); this.render(performance.now()); this.schedule(); return this; }
 setLayout(input: LayoutInput, { animate = false }: { animate?: boolean } = {}) {
  const layout = validate(input), initial = !this.layout, colors = new Map(this.layout?.lines.map(l => [l.id, l.colors]) || []);
  this.layout = layout; layout.lines.forEach(l => { const kept = colors.get(l.id); if (kept) l.colors = [kept[0], kept[1]]; });
  const keep = (set: Set<string>) => new Set([...set].filter(id => layout.lines.some(l => l.id === id)));
  this.selection = keep(this.selection); this.highlighted = keep(this.highlighted); this.activity = keep(this.activity); this.pending = keep(this.pending); this.hovered = keep(this.hovered); this.focused = keep(this.focused);
  this.lineMetadata = new Map([...this.lineMetadata].filter(([id]) => layout.lines.some(l => l.id === id))); this.labelTransforms = new Map([...this.labelTransforms].filter(([id]) => layout.lines.some(l => l.id === id)));
  const shouldAssemble = initial && animate && !this.reduced.matches; this.progress = shouldAssemble ? 0 : 1; this.playing = shouldAssemble; this.assemblyReason = shouldAssemble ? 'first' : null; this.assemblyLast = null; if (initial || shouldAssemble) this.flowLast = null;
  if (!shouldAssemble && !this.flowEpochEstablished) this._establishFlowPhase();
  this.build(); this.render(performance.now()); this.schedule(); return this;
 }
 build() {
  this.inputAbort?.abort(); this.inputAbort = new AbortController();
  const listen = (node: Element, type: string, callback: (event: Event) => void) => node.addEventListener(type, callback, { signal: this.inputAbort!.signal });
  const p = this.p, { nodes, lines, roots } = this.layout, xs = nodes.map(n => n.x), ys = nodes.map(n => n.y), margin = 95; let x = Math.min(...xs) - margin, y = Math.min(...ys) - margin, w = Math.max(...xs) - x + margin, h = Math.max(...ys) - y + margin;
  for (const root of roots) { const n = nodes[root], members = nodes.filter(a => a.root === root), reach = Math.max(...members.map(a => Math.hypot(a.x - n.x, a.y - n.y))); x = Math.min(x, n.x - reach * .28 - margin); y = Math.min(y, n.y - reach * .28 - margin); }
  w = Math.max(...xs) + margin - x; h = Math.max(...ys) + margin - y; this.bounds = [x, y, w, h];
  const lineMarkup = (l: Line) => `<g data-edge="${l.index}" data-line-id="${esc(l.id)}" pointer-events="none"><g data-socket="${l.index}" opacity="0" pointer-events="none"><path d="M${-D} -8V8M${D} -8V8" stroke="url(#${p}rim)" stroke-width="2"/><polygon points="${hex(R - 1)}" fill="none" stroke="url(#${p}edge)" stroke-width=".9"/></g><g data-port="${l.index}"><g clip-path="url(#${p}deploy${l.index})"><g data-slide="${l.index}"><g transform="scale(${l.tubeLength / 256} .78)">${tube(p, l.index)}</g></g></g></g></g>`;
  const nodeMarkup = (n: Node) => `<g data-node="${n.index}" data-node-id="${esc(n.id)}" pointer-events="none"><g data-housing="${n.index}"><g data-orient="${n.index}" transform="rotate(${n.angle})">${connector(p)}</g></g>${roots.includes(n.index) ? `<g data-charge="${n.index}" pointer-events="none"><circle r="20" fill="#8ee9ff" filter="url(#${p}hubglow)" opacity=".7"/><g data-shutters="${n.index}"><polygon points="${hex(12)}" fill="url(#${p}pane)" stroke="#d6f8ff" stroke-opacity=".3" stroke-width=".6"/></g></g>` : ''}</g>`;
  const interactionMarkup = (l: Line) => { const a = nodes[l.a], angle = rad(l.angle), sx = a.x + Math.cos(angle) * l.da, sy = a.y + Math.sin(angle) * l.da, label = 'Select Line ' + esc(l.number); return `<g class="wall-line prism-line-interaction" data-control="${l.index}" data-line="${esc(l.id)}" data-line-id="${esc(l.id)}" transform="translate(${fmt(sx)} ${fmt(sy)}) rotate(${fmt(l.angle)})" role="button" tabindex="0" aria-label="${label}" aria-pressed="false"><title>${label}</title><rect class="hit" data-hit="${l.index}" x="-9" y="-22" width="${fmt(l.tubeLength + 18)}" height="44" rx="12" fill="transparent"/><rect class="outline selection-ring" data-selection="${l.index}" x="-2" y="-18" width="${fmt(l.tubeLength + 4)}" height="36" rx="6" fill="none" opacity="0"/><rect class="highlight-ring" data-highlight-ring="${l.index}" x="0" y="-16" width="${fmt(l.tubeLength)}" height="32" rx="5" fill="none" opacity="0"/><rect class="pending-ring" data-pending-ring="${l.index}" x="-4" y="-20" width="${fmt(l.tubeLength + 8)}" height="40" rx="7" fill="none" opacity="0"/></g>`; };
  const labelMarkup = (l: Line) => { const mark = numeral(p, l.number).replace('<text fill="#e7f5ff"', `<text class="number" data-line-id="${esc(l.id)}" fill="#e7f5ff"`); return `<g class="number-tag" data-label="${l.index}" data-line-id="${esc(l.id)}" visibility="hidden"><g data-label-body="${l.index}">${mark}</g></g>`; };
  this.host.innerHTML = `<svg xmlns="${NS}" viewBox="${this.bounds.map(fmt).join(' ')}" role="group" aria-label="${esc(this.layout.name)}" class="prism-scene" data-prism-mode="${this.mode}"><title>${esc(this.layout.name)}</title><defs>${defs(p)}${lines.map(l => beamDefs(p, l.index) + `<clipPath id="${p}deploy${l.index}"><rect x="0" y="-100" width="${l.tubeLength}" height="200"/></clipPath>`).join('')}</defs><g data-layer="materials" pointer-events="none">${roots.map(root => `<g data-root="${root}"><g data-layer="lines">${lines.filter(l => nodes[l.a].root === root).map(lineMarkup).join('')}</g><g data-layer="connectors" pointer-events="none">${nodes.filter(n => n.root === root).map(nodeMarkup).join('')}</g></g>`).join('')}</g><g data-layer="interaction">${lines.map(interactionMarkup).join('')}</g><g class="numbers" data-layer="numbers" aria-hidden="true">${lines.map(labelMarkup).join('')}</g></svg>`;
  this.svg = this.host.querySelector('svg') as SVGSVGElement; this.parts = {};
  for (const key of ['edge', 'port', 'slide', 'socket', 'node', 'housing', 'orient', 'charge', 'shutters', 'root', 'control', 'hit', 'selection', 'highlight-ring', 'pending-ring', 'label', 'label-body']) this.parts[key] = [...this.svg.querySelectorAll<SVGElement>('[data-' + key + ']')].reduce<Record<string, SVGElement>>((map, element) => (map[element.getAttribute('data-' + key) as string] = element, map), {});
  this.packets = [...this.svg.querySelectorAll<SVGElement>('[data-packet]')]; this.beds = [...this.svg.querySelectorAll<SVGElement>('[data-bed]')]; this.spills = [...this.svg.querySelectorAll<SVGElement>('[data-spill]')]; this.sparks = [...this.svg.querySelectorAll<SVGElement>('[data-spark]')]; this.materialLayers = [...this.svg.querySelectorAll<SVGElement>('[data-layer="lines"]')]; this.rims = nodes.map(n => [...this.parts.orient[n.index].querySelectorAll<SVGElement>('[data-rim]')]);
  for (const line of lines) {
   const control = this.parts.control[line.index], label = this.parts.label[line.index], finishOnPress = () => { if (this.progress < 1) this.finish('interaction'); }, activate = (event: Event) => { if (this.progress < 1) this.finish('interaction'); this.options.onSelect?.(event, line); };
   listen(control, 'pointerdown', finishOnPress); listen(label, 'pointerdown', finishOnPress); listen(control, 'click', activate); listen(label, 'click', activate);
   listen(control, 'keydown', event => { const key = (event as KeyboardEvent).key; if (key === 'Enter' || key === ' ') { event.preventDefault(); activate(event); } });
   listen(control, 'pointerenter', () => { this.hovered.add(line.id); this.updateInteraction(); }); listen(control, 'pointerleave', () => { this.hovered.delete(line.id); this.updateInteraction(); });
   listen(control, 'focus', () => { this.focused.add(line.id); this.updateInteraction(); }); listen(control, 'blur', () => { this.focused.delete(line.id); this.updateInteraction(); }); this.paint(line);
  }
  const restore = [...this.focused][0]; if (restore) { const index = this.layout.lines.find(line => line.id === restore)?.index; if (index !== undefined) (this.parts.control[index] as SVGElement & { focus(options?: FocusOptions): void })?.focus({ preventScroll: true }); }
 }
 paint(line: Line) { for (let z = 0; z < 2; z++) { this.svg.querySelectorAll<SVGElement>('[data-paint="' + line.index + '-' + z + '"]').forEach(el => attr(el, 'stop-color', el.dataset.hot ? pale(line.colors[z]) : line.colors[z])); this.svg.querySelectorAll<SVGElement>('[data-solid="' + line.index + '-' + z + '"]').forEach(el => attr(el, 'fill', el.dataset.hotSolid ? pale(line.colors[z]) : line.colors[z])); } this.paintHubs(); }
 paintHubs() { if (!this.parts?.orient) return; for (const n of this.layout.nodes) { let primary: string | null = null; for (let j = 0; j < 6; j++) { const angle = n.angle + 180 + j * 60, nearest = n.adj.map(a => { const q = this.layout.nodes[a.to], dir = deg(Math.atan2(q.y - n.y, q.x - n.x)); return { ...a, error: Math.abs(mod(dir - angle + 180, 360) - 180) }; }).sort((a, b) => a.error - b.error)[0], line = this.layout.lines[nearest.edge], c = line.colors[line.a === n.index ? 0 : 1], sector = this.rims[n.index][j]; attr(sector.querySelector('[data-hub-tint]'), 'fill', c); attr(sector.querySelector('[data-hub-tint]'), 'opacity', nearest.error < 2 ? .26 : .07); attr(sector.querySelector('[data-hub-edge]'), 'stroke', pale(c)); if (nearest.error < 2) primary = c; } attr(this.parts.orient[n.index].querySelector('[data-hub-aura]'), 'stroke', primary || '#77dfff'); } }
 setColors(id: string | number, colors: string[]) { const line = this.layout.lines.find(item => item.id === String(id)); if (!line) throw Error('Unknown Line ID.'); if (!Array.isArray(colors) || colors.length !== 2 || colors.some(c => !color(c))) throw Error('Provide two hex colors.'); if (line.colors.every((value, index) => value === colors[index])) return this; line.colors = [colors[0], colors[1]]; this.paint(line); this.light(performance.now()); return this; }
 setSelection(ids: Iterable<string | number> | string | null | undefined) { this.selection = lineSet(this.layout, ids, 'Selection'); this.updateInteraction(); return this; }
 setHighlights(ids: Iterable<string | number> | string | null | undefined) { this.highlighted = lineSet(this.layout, ids, 'Highlights'); this.updateInteraction(); return this; }
 setActivity(ids: Iterable<string | number> | string | null | undefined) { this.activity = lineSet(this.layout, ids, 'Activity'); this.light(performance.now()); this.schedule(); return this; }
 setPending(ids: Iterable<string | number> | string | null | undefined) { this.pending = lineSet(this.layout, ids, 'Pending Lines'); this.updateInteraction(); return this; }
 setLineMetadata(entries: Map<string, LineMetadata> | Record<string, LineMetadata | null | undefined> | null | undefined) { const pairs = entries instanceof Map ? [...entries] : Object.entries(entries || {}), next = new Map<string, { ariaLabel?: string; status: string | null }>(); for (const [rawId, raw] of pairs) { const id = String(rawId); if (!this.layout.lines.some(line => line.id === id)) throw Error('Line metadata contains an unknown Line ID.'); const meta = raw || {}; if (meta.ariaLabel !== undefined && typeof meta.ariaLabel !== 'string') throw Error('Line ariaLabel must be text.'); if (meta.status !== undefined && meta.status !== null && typeof meta.status !== 'string') throw Error('Line status must be text or null.'); next.set(id, { ariaLabel: meta.ariaLabel, status: meta.status ?? null }); } this.lineMetadata = next; this.updateInteraction(); return this; }
 setGlow(value: number) { if (!Number.isFinite(value)) throw Error('Glow must be a number.'); this.glow = Math.max(0, Math.min(2, value)); this.light(performance.now()); return this; }
 setMode(mode: Mode) { if (!['work', 'quiet', 'free'].includes(mode)) throw Error('Unknown wall mode.'); if (this.mode !== mode) { this.mode = mode; this.flowLast = null; } this.light(performance.now()); this.schedule(); return this; }
 setDirection(direction: number) { this.direction = direction === -1 ? -1 : 1; this.render(performance.now()); return this; }
 showAllNumbers(value: boolean) { this.showNumbers = !!value; this.updateInteraction(); return this; }
 setLabelTransform(id: string | number, transform: string | null) { const line = this.layout.lines.find(item => item.id === String(id)); if (!line) throw Error('Unknown Line ID.'); if (transform == null) this.labelTransforms.delete(line.id); else if (typeof transform === 'string') this.labelTransforms.set(line.id, transform); else throw Error('Label transform must be an SVG transform string or null.'); this.positionLabels(); return this; }
 replay() { if (this.playing) return this; this.assemblyReason = 'replay'; this.assemblyLast = null; if (this.reduced.matches) { this.progress = 1; this.playing = false; this._establishFlowPhase(); this.render(performance.now()); return this; } this.progress = 0; this.playing = true; this.render(performance.now()); this.schedule(); return this; }
 finish(reason = 'finish') { if (this.progress >= 1 && !this.playing) return this; const completion = reason === 'interaction' ? 'interaction' : this.assemblyReason || reason; return this._completeAssembly(completion); }
 pause() { this._setPauseReason('manual', true); this.render(performance.now()); return this; }
 resume() { this._setPauseReason('manual', false); return this; }
 seek(value: number) { if (!Number.isFinite(value)) throw Error('Progress must be a number.'); this.playing = false; this.assemblyLast = null; this.progress = this.reduced.matches ? 1 : clamp(value); this.render(performance.now()); this.schedule(); return this; }
 render(now: number) {
  const p = this.progress, { nodes, lines, roots, order } = this.layout, turn = -42 + 47 * ease(phase(p, .21, .31)) - 5 * ease(phase(p, .53, .12)); this.turn = turn;
  for (const root of roots) { const n = nodes[root]; n.cx = n.x; n.cy = n.y; n.growth = 1; attr(this.parts.root[root], 'transform', `rotate(${fmt(turn)} ${n.x} ${n.y})`); const charge = this.parts.charge[root], op = (1 - ease(phase(p, .51, .16))) * (.45 + .55 * Math.sin(Math.PI * phase(p, 0, .67))); attr(charge, 'opacity', fmt(op)); attr(charge, 'visibility', p >= .67 ? 'hidden' : 'visible'); }
  for (const idx of order) { const n = nodes[idx]; if (n.parent === null) continue; const l = lines[n.incoming], parent = nodes[n.parent], u = phase(p, l.start, l.duration); l.extension = l.tubeLength * (.17 * ease(u / .25) + .83 * ease((u - .32) / .68)); n.growth = ease(phase(u, .08, .84)); const near = l.reverse ? l.db : l.da, far = l.reverse ? l.da : l.db, angle = rad(l.deployAngle); n.cx = parent.cx + Math.cos(angle) * (near + l.extension + far * n.growth); n.cy = parent.cy + Math.sin(angle) * (near + l.extension + far * n.growth); n.unfold = phase(u, .06, .94); }
  for (const n of nodes) { const el = this.parts.node[n.index]; attr(el, 'transform', `translate(${fmt(n.cx)} ${fmt(n.cy)})`); attr(el, 'visibility', n.growth > 0 ? 'visible' : 'hidden'); attr(this.parts.housing[n.index], 'transform', `scale(${fmt(n.growth)})`); let chain = new DOMMatrix(); const shell = n.parent === null ? 1 : n.unfold, incoming = n.parent === null ? 180 : lines[n.incoming].deployAngle + 180, first = mod(Math.round((incoming - n.angle - 180) / 60), 6); for (let k = 0; k < 6; k++) { const j = mod(first + this.direction * k, 6), piece = this.rims[n.index][j], open = ease(phase(shell, k * .095, .525)), pivot: [number, number] = k === 0 ? point(D, incoming - n.angle) : ((this.direction === 1 ? piece.dataset.pivotA : piece.dataset.pivotB) as string).split(',').map(Number) as [number, number], angle = this.direction * 66 * (1 - open); chain = chain.multiply(new DOMMatrix().translate(pivot[0], pivot[1]).rotate(angle).translate(-pivot[0], -pivot[1])); attr(piece, 'transform', 'matrix(' + [chain.a, chain.b, chain.c, chain.d, chain.e, chain.f].map(fmt).join(' ') + ')'); piece.dataset.open = String(fmt(open)); } }
  for (const l of lines) { const parent = nodes[l.parent]; let fold = 0; if (!l.tree) { const u = phase(p, l.start, l.duration); fold = -60 * (1 - ease(phase(u, .18, .40))); l.extension = l.tubeLength * (.15 * ease(u / .18) + .85 * ease(phase(u, .58, .42))); const socket = this.parts.socket[l.index]; attr(socket, 'opacity', fmt(ease(u / .08) * (1 - ease(phase(u, .65, .3))))); attr(socket, 'visibility', u > 0 && u < .95 ? 'visible' : 'hidden'); } const clip = this.svg.querySelector('#' + this.p + 'deploy' + l.index + ' rect'), spillRoom = 60 * ease(phase(p, .96, .04)); attr(clip, 'x', -spillRoom); attr(clip, 'width', l.tubeLength + spillRoom * 2); const angle = l.deployAngle + fold, near = l.reverse ? l.db : l.da, extension = l.extension || 0, el = this.parts.edge[l.index]; attr(el, 'transform', `translate(${fmt(parent.cx)} ${fmt(parent.cy)}) rotate(${fmt(angle)})`); attr(el, 'visibility', extension > 0 ? 'visible' : 'hidden'); attr(this.parts.port[l.index], 'transform', `translate(${near} 0)`); attr(this.parts.slide[l.index], 'transform', `translate(${fmt(extension - l.tubeLength / 2)} 0)${l.reverse ? ' scale(-1 1)' : ''}`); l.cx = parent.cx + Math.cos(rad(angle)) * (near + extension / 2); l.cy = parent.cy + Math.sin(rad(angle)) * (near + extension / 2); l.currentAngle = angle; l.fold = fold; }
  this.positionLabels(); this.updateInteraction(); this.light(now); this.options.onFrame?.(this.snapshot());
 }
 _labelAnchor(line: Line) { const root = this.layout.nodes[this.layout.nodes[line.a].root], x = line.finalCx, y = line.finalCy, angle = rad(line.angle); let nx = -Math.sin(angle), ny = Math.cos(angle); if (nx * (x - root.x) + ny * (y - root.y) < 0) { nx = -nx; ny = -ny; } return { x, y, nx, ny }; }
 positionLabels() { if (!this.layout || !this.parts?.label) return; for (const line of this.layout.lines) { const anchor = this._labelAnchor(line), fallback = `translate(${fmt(anchor.x + anchor.nx * 27)} ${fmt(anchor.y + anchor.ny * 27)})`, label = this.parts.label[line.index]; attr(label, 'transform', this.labelTransforms.get(line.id) || fallback); label.dataset.anchorX = String(fmt(anchor.x)); label.dataset.anchorY = String(fmt(anchor.y)); label.dataset.normalX = String(fmt(anchor.nx)); label.dataset.normalY = String(fmt(anchor.ny)); } }
 updateInteraction() { if (!this.layout || !this.parts?.control) return; for (const line of this.layout.lines) { const id = line.id, control = this.parts.control[line.index], meta = this.lineMetadata.get(id) || {} as { ariaLabel?: string; status?: string | null }, reasons: string[] = []; if (this.selection.has(id)) reasons.push('selection'); if (this.highlighted.has(id)) reasons.push('highlight'); if (this.hovered.has(id)) reasons.push('hover'); if (this.focused.has(id)) reasons.push('focus'); if (this.showNumbers) reasons.push('all'); control.classList.toggle('selected', this.selection.has(id)); control.classList.toggle('highlighted', this.highlighted.has(id)); control.classList.toggle('hovered', this.hovered.has(id)); control.classList.toggle('focused', this.focused.has(id)); control.classList.toggle('pending', this.pending.has(id)); attr(control, 'aria-pressed', this.selection.has(id)); if (meta.status) control.dataset.status = meta.status; else delete control.dataset.status; const aria = meta.ariaLabel || 'Select Line ' + line.number; attr(control, 'aria-label', aria); const title = control.querySelector('title'); if (title) title.textContent = aria; attr(this.parts.selection[line.index], 'opacity', this.selection.has(id) || this.focused.has(id) ? 1 : 0); attr(this.parts['highlight-ring'][line.index], 'opacity', this.highlighted.has(id) ? 1 : 0); attr(this.parts['pending-ring'][line.index], 'opacity', this.pending.has(id) ? 1 : 0); const label = this.parts.label[line.index]; label.dataset.reasons = reasons.join(' '); attr(label, 'visibility', reasons.length ? 'visible' : 'hidden'); attr(label, 'opacity', fmt(ease(phase(this.progress, .84, .16)))); } }
 light(now: number) {
  if (!this.layout || !this.svg) return;
  const flowAllowed = !this.reduced.matches && this.progress >= 1 && this.mode === 'work' && this.activity.size > 0 && this.pauseReasons.size === 0;
  if (!flowAllowed) this.flowLast = null; else if (this.flowLast === null) this.flowLast = now; else { this.flowElapsed += Math.max(0, (now - this.flowLast) / 1000); this.flowLast = Math.max(this.flowLast, now); }
  const t = (this.flowElapsed / FLOW_SECONDS) % 1; this.lightPhase = t;
  for (const element of this.packets) { const line = this.layout.lines[+(element.dataset.packet as string)], active = this.activity.has(line.id), z = +(element.dataset.zone as string), d = z ? -1 : 1, x = d * (-126 + 126 * Math.min(1, t / .62)); attr(element, 'transform', `translate(${fmt(x)} 0) scale(${d} 1)`); attr(element, 'opacity', flowAllowed && active ? (t < .62 ? 1 : clamp(1 - (t - .62) / .24)) : 0); }
  const base = this.progress < 1 ? .19 : this.mode === 'work' ? .62 : this.mode === 'quiet' ? .34 : .15; for (const element of this.beds) attr(element, 'opacity', element.dataset.hotSolid && base > 0 ? Math.min(1, base + .3) : base);
  const modeGlow = this.progress < 1 ? .35 : this.mode === 'work' ? 1 : this.mode === 'quiet' ? .46 : .2; for (const element of this.spills) { attr(element, 'opacity', Math.min(1, this.glow * modeGlow)); element.querySelectorAll('[data-part=wide-spill]').forEach(spill => attr(spill, 'opacity', this.glow * .64 * modeGlow)); element.querySelectorAll('[data-part=near-spill]').forEach(spill => attr(spill, 'opacity', this.glow * .46 * modeGlow)); }
  this.materialLayers.forEach(layer => { layer.style.filter = this.mode === 'free' ? 'saturate(.35)' : ''; }); const st = (t - .62) / .15, spark = flowAllowed && st > 0 && st < 1 ? Math.min(1, st / .16) * Math.pow(1 - st, 1.8) * 1.45 : 0; this.sparks.forEach(element => attr(element, 'opacity', this.activity.has(this.layout.lines[+(element.dataset.spark as string)].id) ? Math.min(1, spark) : 0));
  this.svg.dataset.prismMode = this.mode; this.svg.dataset.reducedMotion = String(this.reduced.matches);
 }
 _needsFrame() { return !this.destroyed && !!this.layout && this.pauseReasons.size === 0 && !this.reduced.matches && (this.playing || this.progress >= 1 && this.mode === 'work' && this.activity.size > 0); }
 schedule() { if (!this._needsFrame()) { cancelAnimationFrame(this.frameId); this.frameId = 0; return; } if (this.frameId) return; this.frameId = requestAnimationFrame(now => { this.frameId = 0; if (this.playing) { const dt = this.assemblyLast === null ? 0 : Math.max(0, (now - this.assemblyLast) / 1000); this.assemblyLast = now; this.progress = clamp(this.progress + dt * this.speed / this.layout.duration); if (this.progress >= 1) { this.progress = 1; this.playing = false; this.assemblyLast = null; this._establishFlowPhase(); } this.render(now); } else { this.light(now); this.options.onFrame?.(this.snapshot()); } this.schedule(); }); }
 snapshot(): RendererSnapshot { const ordered = (set: Set<string>) => this.layout.lines.filter(line => set.has(line.id)).map(line => line.id); return { progress: this.progress, playing: this.playing, lightPhase: this.lightPhase, selected: ordered(this.selection), highlighted: ordered(this.highlighted), activity: ordered(this.activity), pending: ordered(this.pending), mode: this.mode, pauseReasons: [...this.pauseReasons].sort(), lines: this.layout.lines.length, connectors: this.layout.nodes.length, components: this.layout.roots.length, rootIds: [...this.layout.rootIds], loops: this.layout.lines.filter(l => !l.tree).length, reducedMotion: this.reduced.matches }; }
 exportSVG({ numbers = false }: { numbers?: boolean } = {}) { const copy = this.svg.cloneNode(true) as SVGSVGElement; copy.querySelectorAll('[data-hit],[data-selection],[data-highlight-ring],[data-pending-ring]').forEach(element => element.remove()); if (!numbers) copy.querySelector('[data-layer="numbers"]')?.remove(); copy.querySelectorAll('[tabindex],[role="button"]').forEach(element => { element.removeAttribute('tabindex'); element.removeAttribute('role'); element.removeAttribute('aria-pressed'); }); return new XMLSerializer().serializeToString(copy); }
 destroy() { if (this.destroyed) return; this.destroyed = true; this.inputAbort?.abort(); this.visibilityObserver?.disconnect(); this.removalObserver?.disconnect(); cancelAnimationFrame(this.frameId); this.frameId = 0; document.removeEventListener('visibilitychange', this._hidden); this.reduced.removeEventListener('change', this._reduce); this.host.replaceChildren(); }
}
export const materials = { defs, beamDefs, tube, shell, front, connector, rimPiece, numeral };
export const constants = { connectorRadius: R, innerRadius: INNER, faceDistance: D, tubeLength: 256, tubeWidth: 32, assemblySeconds: ASSEMBLY_SECONDS, flowSeconds: FLOW_SECONDS };
export const utils = { esc, hex, rad, deg, point, fmt, pale, attr, clamp, ease };
